// WARNING: This file is generated by a script, do not edit
import { Collapse } from "../Collapse";
/** This is intended to be exported (with possible extensions) as the default meta object for a story */
export const defaultStoryMeta = {
  title: "Utils/Transitions/Collapse",
  component: Collapse,
};
