// WARNING: This file is generated by a script, do not edit
import { TableRow } from "../TableRow";
/** This is intended to be exported (with possible extensions) as the default meta object for a story */
export const defaultStoryMeta = {
  title: "Data Display/Table/TableRow",
  component: TableRow,
};
