// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { AccordionSummaryTypeMap } from '@material-ui/core/AccordionSummary'
export type AccordionSummaryProps<
  D extends React.ElementType = AccordionSummaryTypeMap['defaultComponent'],
  P = {}
> = MUI.AccordionSummaryProps<D, P>
export const AccordionSummary = <
  D extends React.ElementType = AccordionSummaryTypeMap['defaultComponent'],
  P = {}
>(
  props: AccordionSummaryProps<D, P>,
) => <MUI.AccordionSummary {...props} />
