// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { ListTypeMap } from '@material-ui/core/List'
export type ListProps<
  D extends React.ElementType = ListTypeMap['defaultComponent'],
  P = {}
> = MUI.ListProps<D, P>
export const List = <
  D extends React.ElementType = ListTypeMap['defaultComponent'],
  P = {}
>(
  props: ListProps<D, P>,
) => <MUI.List {...props} />
