// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUITabs,
  TabsProps as MUITabsProps,
  TabsTypeMap,
} from '@material-ui/core/Tabs'

/**
 * Props for Tabs
 */
export type TabsProps<
  D extends React.ElementType = TabsTypeMap['defaultComponent'],
  P = {}
> = MUITabsProps<D, P> & { ref?: React.ForwardedRef<HTMLButtonElement> }

/**
 * Tabs
 */
export const Tabs = React.forwardRef((props, ref) => (
  <MUITabs ref={ref} {...props} />
)) as <D extends React.ElementType = TabsTypeMap['defaultComponent'], P = {}>(
  props: TabsProps<D, P>,
) => JSX.Element
