// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { TabsTypeMap } from '@material-ui/core/Tabs'
export type TabsProps<
  D extends React.ElementType = TabsTypeMap['defaultComponent'],
  P = {}
> = MUI.TabsProps<D, P>
export const Tabs = <
  D extends React.ElementType = TabsTypeMap['defaultComponent'],
  P = {}
>(
  props: TabsProps<D, P>,
) => <MUI.Tabs {...props} />
