// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUITabs,
  TabsProps as MUITabsProps,
  TabsTypeMap,
} from '@material-ui/core/Tabs'
export type TabsProps<
  D extends React.ElementType = TabsTypeMap['defaultComponent'],
  P = {}
> = MUITabsProps<D, P>
export const Tabs = <
  D extends React.ElementType = TabsTypeMap['defaultComponent'],
  P = {}
>(
  props: TabsProps<D, P>,
) => <MUITabs {...props} />
