// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { ButtonBaseTypeMap } from '@material-ui/core/ButtonBase'
export type ButtonBaseProps<
  D extends React.ElementType = ButtonBaseTypeMap['defaultComponent'],
  P = {}
> = MUI.ButtonBaseProps<D, P>
export const ButtonBase = <
  D extends React.ElementType = ButtonBaseTypeMap['defaultComponent'],
  P = {}
>(
  props: ButtonBaseProps<D, P>,
) => <MUI.ButtonBase {...props} />
