// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIRadio,
  RadioProps as MUIRadioProps,
} from '@material-ui/core/Radio'
export type RadioProps = MUIRadioProps
export const Radio = (props: RadioProps) => <MUIRadio {...props} />
