// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type RadioProps = MUI.RadioProps
export const Radio = (props: RadioProps) => <MUI.Radio {...props} />
