// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIFab,
  FabProps as MUIFabProps,
  FabTypeMap,
} from '@mui/material/Fab'

/**
 * Props for Fab
 */
export type FabProps<
  D extends React.ElementType = FabTypeMap['defaultComponent'],
  P = {}
> = MUIFabProps<D, P> & { ref?: React.ForwardedRef<HTMLButtonElement> }

/**
 * Fab
 */
export const Fab = React.forwardRef((props, ref) => (
  <MUIFab ref={ref} {...props} />
)) as <D extends React.ElementType = FabTypeMap['defaultComponent'], P = {}>(
  props: FabProps<D, P>,
) => JSX.Element
