// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { FabTypeMap } from '@material-ui/core/Fab'
export type FabProps<
  D extends React.ElementType = FabTypeMap['defaultComponent'],
  P = {}
> = MUI.FabProps<D, P>
export const Fab = <
  D extends React.ElementType = FabTypeMap['defaultComponent'],
  P = {}
>(
  props: FabProps<D, P>,
) => <MUI.Fab {...props} />
