// WARNING: This file is generated by a script, do not edit
import { Container } from '../Container'
/** This is intended to be exported (with possible extensions) as the default meta object for a story */
export const defaultStoryMeta = {
  title: 'Layout/Container',
  component: Container,
}
