// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIScopedCssBaseline,
  ScopedCssBaselineProps as MUIScopedCssBaselineProps,
  ScopedCssBaselineTypeMap,
} from '@material-ui/core/ScopedCssBaseline'
export type ScopedCssBaselineProps<
  D extends React.ElementType = ScopedCssBaselineTypeMap['defaultComponent'],
  P = {}
> = MUIScopedCssBaselineProps<D, P>
export const ScopedCssBaseline = <
  D extends React.ElementType = ScopedCssBaselineTypeMap['defaultComponent'],
  P = {}
>(
  props: ScopedCssBaselineProps<D, P>,
) => <MUIScopedCssBaseline {...props} />
