// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { ScopedCssBaselineTypeMap } from '@material-ui/core/ScopedCssBaseline'
export type ScopedCssBaselineProps<
  D extends React.ElementType = ScopedCssBaselineTypeMap['defaultComponent'],
  P = {}
> = MUI.ScopedCssBaselineProps<D, P>
export const ScopedCssBaseline = <
  D extends React.ElementType = ScopedCssBaselineTypeMap['defaultComponent'],
  P = {}
>(
  props: ScopedCssBaselineProps<D, P>,
) => <MUI.ScopedCssBaseline {...props} />
