// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIScopedCssBaseline,
  ScopedCssBaselineProps as MUIScopedCssBaselineProps,
  ScopedCssBaselineTypeMap,
} from '@mui/material/ScopedCssBaseline'

/**
 * Props for ScopedCssBaseline
 */
export type ScopedCssBaselineProps<
  D extends React.ElementType = ScopedCssBaselineTypeMap['defaultComponent'],
  P = {},
> = MUIScopedCssBaselineProps<D, P> & {
  ref?: React.ForwardedRef<HTMLDivElement>
}

/**
 * ScopedCssBaseline
 */
export const ScopedCssBaseline = React.forwardRef((props, ref) => (
  <MUIScopedCssBaseline ref={ref} {...props} />
)) as <
  D extends React.ElementType = ScopedCssBaselineTypeMap['defaultComponent'],
  P = {},
>(
  props: ScopedCssBaselineProps<D, P>,
) => JSX.Element
