// WARNING: This file is generated by a script, do not edit
import React from "react";
import {
  default as MUITimelineConnector,
  TimelineConnectorProps as MUITimelineConnectorProps,
} from "@mui/lab/TimelineConnector";

/**
 * Props for TimelineConnector
 */
export type TimelineConnectorProps = MUITimelineConnectorProps & {
  ref?: React.ForwardedRef<unknown>;
};

/**
 * TimelineConnector
 */
export const TimelineConnector = React.forwardRef((props, ref) => (
  <MUITimelineConnector ref={ref} {...props} />
)) as (props: TimelineConnectorProps) => JSX.Element;
