// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type GlobalStylesProps = MUI.GlobalStylesProps
export const GlobalStyles = (props: GlobalStylesProps) => (
  <MUI.GlobalStyles {...props} />
)
