// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { ButtonBaseTypeMap } from '@material-ui/core/ButtonBase'
export type CardActionAreaProps<
  D extends React.ElementType = ButtonBaseTypeMap['defaultComponent'],
  P = {}
> = MUI.CardActionAreaProps<D, P>
export const CardActionArea = <
  D extends React.ElementType = ButtonBaseTypeMap['defaultComponent'],
  P = {}
>(
  props: CardActionAreaProps<D, P>,
) => <MUI.CardActionArea {...props} />
