// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { InputAdornmentTypeMap } from '@material-ui/core/InputAdornment'
export type InputAdornmentProps<
  D extends React.ElementType = InputAdornmentTypeMap['defaultComponent'],
  P = {}
> = MUI.InputAdornmentProps<D, P>
export const InputAdornment = <
  D extends React.ElementType = InputAdornmentTypeMap['defaultComponent'],
  P = {}
>(
  props: InputAdornmentProps<D, P>,
) => <MUI.InputAdornment {...props} />
