// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIInputAdornment,
  InputAdornmentProps as MUIInputAdornmentProps,
  InputAdornmentTypeMap,
} from '@material-ui/core/InputAdornment'
export type InputAdornmentProps<
  D extends React.ElementType = InputAdornmentTypeMap['defaultComponent'],
  P = {}
> = MUIInputAdornmentProps<D, P>
export const InputAdornment = <
  D extends React.ElementType = InputAdornmentTypeMap['defaultComponent'],
  P = {}
>(
  props: InputAdornmentProps<D, P>,
) => <MUIInputAdornment {...props} />
