// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  CardMediaProps as MUICardMediaProps,
  default as MUICardMedia,
} from '@mui/material/CardMedia'

/**
 * Props for CardMedia
 */
export type CardMediaProps<
  D extends React.ElementType = 'div',
  P = {},
> = MUICardMediaProps<D, P> & { ref?: React.ForwardedRef<HTMLDivElement> }

/**
 * CardMedia
 */
export const CardMedia = React.forwardRef((props, ref) => (
  <MUICardMedia ref={ref} {...props} />
)) as <D extends React.ElementType = 'div', P = {}>(
  props: CardMediaProps<D, P>,
) => JSX.Element
