// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUITableContainer,
  TableContainerProps as MUITableContainerProps,
  TableContainerTypeMap,
} from '@material-ui/core/TableContainer'
export type TableContainerProps<
  D extends React.ElementType = TableContainerTypeMap['defaultComponent'],
  P = {}
> = MUITableContainerProps<D, P>
export const TableContainer = <
  D extends React.ElementType = TableContainerTypeMap['defaultComponent'],
  P = {}
>(
  props: TableContainerProps<D, P>,
) => <MUITableContainer {...props} />
