// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { TableContainerTypeMap } from '@material-ui/core/TableContainer'
export type TableContainerProps<
  D extends React.ElementType = TableContainerTypeMap['defaultComponent'],
  P = {}
> = MUI.TableContainerProps<D, P>
export const TableContainer = <
  D extends React.ElementType = TableContainerTypeMap['defaultComponent'],
  P = {}
>(
  props: TableContainerProps<D, P>,
) => <MUI.TableContainer {...props} />
