// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIFade,
  FadeProps as MUIFadeProps,
} from '@material-ui/core/Fade'
export type FadeProps = MUIFadeProps
export const Fade = (props: FadeProps) => <MUIFade {...props} />
