// WARNING: This file is generated by a script, do not edit
import React from "react";
import {
  default as MUIFade,
  FadeProps as MUIFadeProps,
} from "@mui/material/Fade";

/**
 * Props for Fade
 */
export type FadeProps = MUIFadeProps & { ref?: React.ForwardedRef<unknown> };

/**
 * Fade
 */
export const Fade = React.forwardRef((props, ref) => (
  <MUIFade ref={ref} {...props} />
)) as (props: FadeProps) => JSX.Element;
