// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIFormGroup,
  FormGroupProps as MUIFormGroupProps,
} from '@material-ui/core/FormGroup'
export type FormGroupProps = MUIFormGroupProps
export const FormGroup = (props: FormGroupProps) => <MUIFormGroup {...props} />
