// WARNING: This file is generated by a script, do not edit
import React from "react";
import {
  default as MUIFormGroup,
  FormGroupProps as MUIFormGroupProps,
} from "@mui/material/FormGroup";

/**
 * Props for FormGroup
 */
export type FormGroupProps = MUIFormGroupProps & {
  ref?: React.ForwardedRef<unknown>;
};

/**
 * FormGroup
 */
export const FormGroup = React.forwardRef((props, ref) => (
  <MUIFormGroup ref={ref} {...props} />
)) as (props: FormGroupProps) => JSX.Element;
