// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type ListItemIconProps = MUI.ListItemIconProps
export const ListItemIcon = (props: ListItemIconProps) => (
  <MUI.ListItemIcon {...props} />
)
