// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIFormHelperText,
  FormHelperTextProps as MUIFormHelperTextProps,
  FormHelperTextTypeMap,
} from '@mui/material/FormHelperText'

/**
 * Props for FormHelperText
 */
export type FormHelperTextProps<
  D extends React.ElementType = FormHelperTextTypeMap['defaultComponent'],
  P = {},
> = MUIFormHelperTextProps<D, P> & {
  ref?: React.ForwardedRef<HTMLParagraphElement>
}

/**
 * FormHelperText
 */
export const FormHelperText = React.forwardRef((props, ref) => (
  <MUIFormHelperText ref={ref} {...props} />
)) as <
  D extends React.ElementType = FormHelperTextTypeMap['defaultComponent'],
  P = {},
>(
  props: FormHelperTextProps<D, P>,
) => JSX.Element
