// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { FormHelperTextTypeMap } from '@material-ui/core/FormHelperText'
export type FormHelperTextProps<
  D extends React.ElementType = FormHelperTextTypeMap['defaultComponent'],
  P = {}
> = MUI.FormHelperTextProps<D, P>
export const FormHelperText = <
  D extends React.ElementType = FormHelperTextTypeMap['defaultComponent'],
  P = {}
>(
  props: FormHelperTextProps<D, P>,
) => <MUI.FormHelperText {...props} />
