// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type TextFieldProps = MUI.TextFieldProps
export const TextField = (props: TextFieldProps) => <MUI.TextField {...props} />
