// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUITextField,
  TextFieldProps as MUITextFieldProps,
} from '@material-ui/core/TextField'
export type TextFieldProps = MUITextFieldProps
export const TextField = (props: TextFieldProps) => <MUITextField {...props} />
