// WARNING: This file is generated by a script, do not edit
import { ButtonGroup } from "../ButtonGroup";
/** This is intended to be exported (with possible extensions) as the default meta object for a story */
export const defaultStoryMeta = {
  title: "Inputs/ButtonGroup",
  component: ButtonGroup,
};
