image: node:lts

cache:
  paths:
    - node_modules/
    - .yarn

stages:
  - build
  - lint
  - test

before_script:
  - yarn install --frozen-lockfile

Build:
  stage: build
  script:
    - yarn build

Lint:
  stage: lint
  script:
    - yarn eslint
    - yarn prettier:check

Test:
  stage: test
  script:
    - yarn test
