image: node:lts

cache:
  paths:
    - node_modules/
    - .yarn

stages:
  - build
  - test
  - storybook

before_script:
  - yarn install --frozen-lockfile

Build:
  stage: build
  script:
    - yarn build

Test:
  stage: test
  script:
    - yarn test
