nodeLinker: node-modules

npmScopes:
  simspace:
    npmPublishRegistry: "https://gitlab.com/api/v4/projects/35724628/packages/npm/"
    npmRegistryServer: "https://gitlab.com/api/v4/packages/npm/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
