nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.2.1.cjs

npmScopes:
  simspace:
    npmPublishRegistry: 'https://gitlab.com/api/v4/projects/35724628/packages/npm/'
    npmRegistryServer: 'https://gitlab.com/api/v4/packages/npm/'
