// WARNING: This file is generated by a script, do not edit
import React from "react";
import {
  CardHeaderProps as MUICardHeaderProps,
  CardHeaderTypeMap,
  default as MUICardHeader,
} from "@mui/material/CardHeader";

/**
 * Props for CardHeader
 */
export type CardHeaderProps<
  DefaultComponent extends React.ElementType = CardHeaderTypeMap["defaultComponent"],
  Props = {},
  TitleTypographyComponent extends React.ElementType = "span",
  SubheaderTypographyComponent extends React.ElementType = "span"
> = MUICardHeaderProps<
  DefaultComponent,
  Props,
  TitleTypographyComponent,
  SubheaderTypographyComponent
> & { ref?: React.ForwardedRef<HTMLDivElement> };

/**
 * CardHeader
 */
export const CardHeader = React.forwardRef((props, ref) => (
  <MUICardHeader ref={ref} {...props} />
)) as <
  DefaultComponent extends React.ElementType = CardHeaderTypeMap["defaultComponent"],
  Props = {},
  TitleTypographyComponent extends React.ElementType = "span",
  SubheaderTypographyComponent extends React.ElementType = "span"
>(
  props: CardHeaderProps<
    DefaultComponent,
    Props,
    TitleTypographyComponent,
    SubheaderTypographyComponent
  >
) => JSX.Element;
