// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUICardHeader,
  CardHeaderProps as MUICardHeaderProps,
  CardHeaderTypeMap,
} from '@material-ui/core/CardHeader'
export type CardHeaderProps<
  DefaultComponent extends React.ElementType = CardHeaderTypeMap['defaultComponent'],
  Props = {},
  TitleTypographyComponent extends React.ElementType = 'span',
  SubheaderTypographyComponent extends React.ElementType = 'span'
> = MUICardHeaderProps<
  DefaultComponent,
  Props,
  TitleTypographyComponent,
  SubheaderTypographyComponent
>
export const CardHeader = <
  DefaultComponent extends React.ElementType = CardHeaderTypeMap['defaultComponent'],
  Props = {},
  TitleTypographyComponent extends React.ElementType = 'span',
  SubheaderTypographyComponent extends React.ElementType = 'span'
>(
  props: CardHeaderProps<
    DefaultComponent,
    Props,
    TitleTypographyComponent,
    SubheaderTypographyComponent
  >,
) => <MUICardHeader {...props} />
