// WARNING: This file is generated by a script, do not edit
import { Unstable_TrapFocus } from "../Unstable_TrapFocus";
/** This is intended to be exported (with possible extensions) as the default meta object for a story */
export const defaultStoryMeta = {
  title: "Utils/Unstable_TrapFocus",
  component: Unstable_TrapFocus,
};
