// WARNING: This file is generated by a script, do not edit
import { Zoom } from '../Zoom'
/** This is intended to be exported (with possible extensions) as the default meta object for a story */
export const defaultStoryMeta = {
  title: 'Utils/Transitions/Zoom',
  component: Zoom,
}
