// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIDrawer,
  DrawerProps as MUIDrawerProps,
} from '@material-ui/core/Drawer'

/**
 * Props for Drawer
 */
export type DrawerProps = MUIDrawerProps & { ref?: React.ForwardedRef<unknown> }

/**
 * Drawer
 */
export const Drawer = React.forwardRef((props, ref) => (
  <MUIDrawer ref={ref} {...props} />
)) as (props: DrawerProps) => JSX.Element
