// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIDrawer,
  DrawerProps as MUIDrawerProps,
} from '@material-ui/core/Drawer'
export type DrawerProps = MUIDrawerProps
export const Drawer = (props: DrawerProps) => <MUIDrawer {...props} />
