// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUITypography,
  TypographyProps as MUITypographyProps,
  TypographyTypeMap,
} from '@material-ui/core/Typography'
export type TypographyProps<
  D extends React.ElementType = TypographyTypeMap['defaultComponent'],
  P = {}
> = MUITypographyProps<D, P>
export const Typography = <
  D extends React.ElementType = TypographyTypeMap['defaultComponent'],
  P = {}
>(
  props: TypographyProps<D, P>,
) => <MUITypography {...props} />
