// WARNING: This file is generated by a script, do not edit
import React from "react";
import {
  default as MUITypography,
  TypographyProps as MUITypographyProps,
  TypographyTypeMap,
} from "@mui/material/Typography";

/**
 * Props for Typography
 */
export type TypographyProps<
  D extends React.ElementType = TypographyTypeMap["defaultComponent"],
  P = {}
> = MUITypographyProps<D, P> & { ref?: React.ForwardedRef<HTMLSpanElement> };

/**
 * Typography
 */
export const Typography = React.forwardRef((props, ref) => (
  <MUITypography ref={ref} {...props} />
)) as <
  D extends React.ElementType = TypographyTypeMap["defaultComponent"],
  P = {}
>(
  props: TypographyProps<D, P>
) => JSX.Element;
