// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { TypographyTypeMap } from '@material-ui/core/Typography'
export type TypographyProps<
  D extends React.ElementType = TypographyTypeMap['defaultComponent'],
  P = {}
> = MUI.TypographyProps<D, P>
export const Typography = <
  D extends React.ElementType = TypographyTypeMap['defaultComponent'],
  P = {}
>(
  props: TypographyProps<D, P>,
) => <MUI.Typography {...props} />
