// WARNING: This file is generated by a script, do not edit
import { MobileStepper } from '../MobileStepper'
/** This is intended to be exported (with possible extensions) as the default meta object for a story */
export const defaultStoryMeta = {
  title: 'Navigation/MobileStepper',
  component: MobileStepper,
}
