// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { BoxTypeMap } from '@material-ui/core/Box'
export type BoxProps<
  D extends React.ElementType = BoxTypeMap['defaultComponent'],
  P = {}
> = MUI.BoxProps<D, P>
export const Box = <
  D extends React.ElementType = BoxTypeMap['defaultComponent'],
  P = {}
>(
  props: BoxProps<D, P>,
) => <MUI.Box {...props} />
