// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIBox,
  BoxProps as MUIBoxProps,
  BoxTypeMap,
} from '@mui/material/Box'

/**
 * Props for Box
 */
export type BoxProps<
  D extends React.ElementType = BoxTypeMap['defaultComponent'],
  P = {},
> = MUIBoxProps<D, P> & { ref?: React.ForwardedRef<unknown> }

/**
 * Box
 */
export const Box = React.forwardRef((props, ref) => (
  <MUIBox ref={ref} {...props} />
)) as <D extends React.ElementType = BoxTypeMap['defaultComponent'], P = {}>(
  props: BoxProps<D, P>,
) => JSX.Element
