// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIListItemText,
  ListItemTextProps as MUIListItemTextProps,
} from '@material-ui/core/ListItemText'
export type ListItemTextProps<
  PrimaryTypographyComponent extends React.ElementType = 'span',
  SecondaryTypographyComponent extends React.ElementType = 'p'
> = MUIListItemTextProps<
  PrimaryTypographyComponent,
  SecondaryTypographyComponent
> & { ref?: React.ForwardedRef<unknown> }
export const ListItemText = React.forwardRef((props, ref) => (
  <MUIListItemText ref={ref} {...props} />
)) as <
  PrimaryTypographyComponent extends React.ElementType = 'span',
  SecondaryTypographyComponent extends React.ElementType = 'p'
>(
  props: ListItemTextProps<
    PrimaryTypographyComponent,
    SecondaryTypographyComponent
  >,
) => ReturnType<typeof MUIListItemText>
