// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIListItemAvatar,
  ListItemAvatarProps as MUIListItemAvatarProps,
} from '@material-ui/core/ListItemAvatar'
export type ListItemAvatarProps = MUIListItemAvatarProps & {
  ref?: React.ForwardedRef<unknown>
}
export const ListItemAvatar = React.forwardRef((props, ref) => (
  <MUIListItemAvatar ref={ref} {...props} />
)) as (props: ListItemAvatarProps) => ReturnType<typeof MUIListItemAvatar>
