// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { ButtonTypeMap } from '@material-ui/core/Button'
export type ButtonProps<
  D extends React.ElementType = ButtonTypeMap['defaultComponent'],
  P = {}
> = MUI.ButtonProps<D, P>
export const Button = <
  D extends React.ElementType = ButtonTypeMap['defaultComponent'],
  P = {}
>(
  props: ButtonProps<D, P>,
) => <MUI.Button {...props} />
