// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { PaperTypeMap } from '@material-ui/core/Paper'
export type PaperProps<
  D extends React.ElementType = PaperTypeMap['defaultComponent'],
  P = {}
> = MUI.PaperProps<D, P>
export const Paper = <
  D extends React.ElementType = PaperTypeMap['defaultComponent'],
  P = {}
>(
  props: PaperProps<D, P>,
) => <MUI.Paper {...props} />
