// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIPaper,
  PaperProps as MUIPaperProps,
  PaperTypeMap,
} from '@material-ui/core/Paper'
export type PaperProps<
  D extends React.ElementType = PaperTypeMap['defaultComponent'],
  P = {}
> = MUIPaperProps<D, P> & { ref?: React.ForwardedRef<HTMLDivElement> }
export const Paper = React.forwardRef((props, ref) => (
  <MUIPaper ref={ref} {...props} />
)) as <D extends React.ElementType = PaperTypeMap['defaultComponent'], P = {}>(
  props: PaperProps<D, P>,
) => ReturnType<typeof MUIPaper>
