// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIPaper,
  PaperProps as MUIPaperProps,
  PaperTypeMap,
} from '@material-ui/core/Paper'
export type PaperProps<
  D extends React.ElementType = PaperTypeMap['defaultComponent'],
  P = {}
> = MUIPaperProps<D, P>
export const Paper = <
  D extends React.ElementType = PaperTypeMap['defaultComponent'],
  P = {}
>(
  props: PaperProps<D, P>,
) => <MUIPaper {...props} />
