// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIHidden,
  HiddenProps as MUIHiddenProps,
} from '@mui/material/Hidden'

/**
 * Props for Hidden
 */
export type HiddenProps = MUIHiddenProps & {
  ref?: React.ForwardedRef<unknown>
}

/**
 * Hidden
 */
export const Hidden = React.forwardRef((props, ref) => (
  <MUIHidden ref={ref} {...props} />
)) as (props: HiddenProps) => JSX.Element
