// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type HiddenProps = MUI.HiddenProps
export const Hidden = (props: HiddenProps) => <MUI.Hidden {...props} />
