// WARNING: This file is generated by a script, do not edit
import { AlertTitle } from "../AlertTitle";
/** This is intended to be exported (with possible extensions) as the default meta object for a story */
export const defaultStoryMeta = {
  title: "Feedback/Alert/AlertTitle",
  component: AlertTitle,
};
