// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { BreadcrumbsTypeMap } from '@material-ui/core/Breadcrumbs'
export type BreadcrumbsProps<
  D extends React.ElementType = BreadcrumbsTypeMap['defaultComponent'],
  P = {}
> = MUI.BreadcrumbsProps<D, P>
export const Breadcrumbs = <
  D extends React.ElementType = BreadcrumbsTypeMap['defaultComponent'],
  P = {}
>(
  props: BreadcrumbsProps<D, P>,
) => <MUI.Breadcrumbs {...props} />
