// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIBreadcrumbs,
  BreadcrumbsProps as MUIBreadcrumbsProps,
  BreadcrumbsTypeMap,
} from '@material-ui/core/Breadcrumbs'
export type BreadcrumbsProps<
  D extends React.ElementType = BreadcrumbsTypeMap['defaultComponent'],
  P = {}
> = MUIBreadcrumbsProps<D, P>
export const Breadcrumbs = <
  D extends React.ElementType = BreadcrumbsTypeMap['defaultComponent'],
  P = {}
>(
  props: BreadcrumbsProps<D, P>,
) => <MUIBreadcrumbs {...props} />
