// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type MobileStepperProps = MUI.MobileStepperProps
export const MobileStepper = (props: MobileStepperProps) => (
  <MUI.MobileStepper {...props} />
)
