// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIMobileStepper,
  MobileStepperProps as MUIMobileStepperProps,
} from '@material-ui/core/MobileStepper'
export type MobileStepperProps = MUIMobileStepperProps
export const MobileStepper = (props: MobileStepperProps) => (
  <MUIMobileStepper {...props} />
)
