// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIStepIcon,
  StepIconProps as MUIStepIconProps,
} from '@material-ui/core/StepIcon'
export type StepIconProps = MUIStepIconProps
export const StepIcon = (props: StepIconProps) => <MUIStepIcon {...props} />
