// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type StepIconProps = MUI.StepIconProps
export const StepIcon = (props: StepIconProps) => <MUI.StepIcon {...props} />
