// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIStepIcon,
  StepIconProps as MUIStepIconProps,
} from '@material-ui/core/StepIcon'

/**
 * Props for StepIcon
 */
export type StepIconProps = MUIStepIconProps & {
  ref?: React.ForwardedRef<unknown>
}

/**
 * StepIcon
 */
export const StepIcon = React.forwardRef((props, ref) => (
  <MUIStepIcon ref={ref} {...props} />
)) as (props: StepIconProps) => JSX.Element
