// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIMobileDatePicker,
  MobileDatePickerProps as MUIMobileDatePickerProps,
} from '@material-ui/lab/MobileDatePicker'

/**
 * Props for MobileDatePicker
 */
export type MobileDatePickerProps<
  TDate = unknown
> = MUIMobileDatePickerProps<TDate> & {
  ref?: React.ForwardedRef<HTMLDivElement>
}

/**
 * MobileDatePicker
 */
export const MobileDatePicker = React.forwardRef((props, ref) => (
  <MUIMobileDatePicker ref={ref} {...props} />
)) as <TDate = unknown>(props: MobileDatePickerProps<TDate>) => JSX.Element
