// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIAccordionActions,
  AccordionActionsProps as MUIAccordionActionsProps,
} from '@material-ui/core/AccordionActions'
export type AccordionActionsProps = MUIAccordionActionsProps
export const AccordionActions = (props: AccordionActionsProps) => (
  <MUIAccordionActions {...props} />
)
