// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIAccordionActions,
  AccordionActionsProps as MUIAccordionActionsProps,
} from '@mui/material/AccordionActions'

/**
 * Props for AccordionActions
 */
export type AccordionActionsProps = MUIAccordionActionsProps & {
  ref?: React.ForwardedRef<unknown>
}

/**
 * AccordionActions
 */
export const AccordionActions = React.forwardRef((props, ref) => (
  <MUIAccordionActions ref={ref} {...props} />
)) as (props: AccordionActionsProps) => JSX.Element
