// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUILinearProgress,
  LinearProgressProps as MUILinearProgressProps,
} from '@material-ui/core/LinearProgress'
export type LinearProgressProps = MUILinearProgressProps
export const LinearProgress = (props: LinearProgressProps) => (
  <MUILinearProgress {...props} />
)
