// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUILinearProgress,
  LinearProgressProps as MUILinearProgressProps,
} from '@material-ui/core/LinearProgress'

/**
 * Props for LinearProgress
 */
export type LinearProgressProps = MUILinearProgressProps & {
  ref?: React.ForwardedRef<unknown>
}

/**
 * LinearProgress
 */
export const LinearProgress = React.forwardRef((props, ref) => (
  <MUILinearProgress ref={ref} {...props} />
)) as (props: LinearProgressProps) => JSX.Element
