// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type ListItemSecondaryActionProps = MUI.ListItemSecondaryActionProps
export const ListItemSecondaryAction = (
  props: ListItemSecondaryActionProps,
) => <MUI.ListItemSecondaryAction {...props} />
