// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIPortal,
  PortalProps as MUIPortalProps,
} from '@material-ui/core/Portal'

/**
 * Props for Portal
 */
export type PortalProps = MUIPortalProps & { ref?: React.ForwardedRef<unknown> }

/**
 * Portal
 */
export const Portal = React.forwardRef((props, ref) => (
  <MUIPortal ref={ref} {...props} />
)) as (props: PortalProps) => JSX.Element
