// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type PortalProps = MUI.PortalProps
export const Portal = (props: PortalProps) => <MUI.Portal {...props} />
