// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { TableHeadTypeMap } from '@material-ui/core/TableHead'
export type TableHeadProps<
  D extends React.ElementType = TableHeadTypeMap['defaultComponent'],
  P = {}
> = MUI.TableHeadProps<D, P>
export const TableHead = <
  D extends React.ElementType = TableHeadTypeMap['defaultComponent'],
  P = {}
>(
  props: TableHeadProps<D, P>,
) => <MUI.TableHead {...props} />
