// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUITableHead,
  TableHeadProps as MUITableHeadProps,
  TableHeadTypeMap,
} from '@material-ui/core/TableHead'
export type TableHeadProps<
  D extends React.ElementType = TableHeadTypeMap['defaultComponent'],
  P = {}
> = MUITableHeadProps<D, P>
export const TableHead = <
  D extends React.ElementType = TableHeadTypeMap['defaultComponent'],
  P = {}
>(
  props: TableHeadProps<D, P>,
) => <MUITableHead {...props} />
