// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { ToolbarTypeMap } from '@material-ui/core/Toolbar'
export type ToolbarProps<
  D extends React.ElementType = ToolbarTypeMap['defaultComponent'],
  P = {}
> = MUI.ToolbarProps<D, P>
export const Toolbar = <
  D extends React.ElementType = ToolbarTypeMap['defaultComponent'],
  P = {}
>(
  props: ToolbarProps<D, P>,
) => <MUI.Toolbar {...props} />
