// WARNING: This file is generated by a script, do not edit
import React from "react";
import {
  default as MUIToolbar,
  ToolbarProps as MUIToolbarProps,
  ToolbarTypeMap,
} from "@mui/material/Toolbar";

/**
 * Props for Toolbar
 */
export type ToolbarProps<
  D extends React.ElementType = ToolbarTypeMap["defaultComponent"],
  P = {}
> = MUIToolbarProps<D, P> & { ref?: React.ForwardedRef<HTMLDivElement> };

/**
 * Toolbar
 */
export const Toolbar = React.forwardRef((props, ref) => (
  <MUIToolbar ref={ref} {...props} />
)) as <
  D extends React.ElementType = ToolbarTypeMap["defaultComponent"],
  P = {}
>(
  props: ToolbarProps<D, P>
) => JSX.Element;
