// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIToolbar,
  ToolbarProps as MUIToolbarProps,
  ToolbarTypeMap,
} from '@material-ui/core/Toolbar'
export type ToolbarProps<
  D extends React.ElementType = ToolbarTypeMap['defaultComponent'],
  P = {}
> = MUIToolbarProps<D, P>
export const Toolbar = <
  D extends React.ElementType = ToolbarTypeMap['defaultComponent'],
  P = {}
>(
  props: ToolbarProps<D, P>,
) => <MUIToolbar {...props} />
