// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type CollapseProps = MUI.CollapseProps
export const Collapse = (props: CollapseProps) => <MUI.Collapse {...props} />
