// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUICollapse,
  CollapseProps as MUICollapseProps,
} from '@material-ui/core/Collapse'
export type CollapseProps = MUICollapseProps & {
  ref?: React.ForwardedRef<unknown>
}
export const Collapse = React.forwardRef((props, ref) => (
  <MUICollapse ref={ref} {...props} />
)) as (props: CollapseProps) => ReturnType<typeof MUICollapse>
