// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIAlertTitle,
  AlertTitleProps as MUIAlertTitleProps,
} from '@material-ui/core/AlertTitle'
export type AlertTitleProps = MUIAlertTitleProps
export const AlertTitle = (props: AlertTitleProps) => (
  <MUIAlertTitle {...props} />
)
