// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type AlertTitleProps = MUI.AlertTitleProps
export const AlertTitle = (props: AlertTitleProps) => (
  <MUI.AlertTitle {...props} />
)
