// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIAlertTitle,
  AlertTitleProps as MUIAlertTitleProps,
} from '@material-ui/core/AlertTitle'

/**
 * Props for AlertTitle
 */
export type AlertTitleProps = MUIAlertTitleProps & {
  ref?: React.ForwardedRef<unknown>
}

/**
 * AlertTitle
 */
export const AlertTitle = React.forwardRef((props, ref) => (
  <MUIAlertTitle ref={ref} {...props} />
)) as (props: AlertTitleProps) => JSX.Element
