// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type MenuListProps = MUI.MenuListProps
export const MenuList = (props: MenuListProps) => <MUI.MenuList {...props} />
