// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIMenuList,
  MenuListProps as MUIMenuListProps,
} from '@material-ui/core/MenuList'

/**
 * Props for MenuList
 */
export type MenuListProps = MUIMenuListProps & {
  ref?: React.ForwardedRef<unknown>
}

/**
 * MenuList
 */
export const MenuList = React.forwardRef((props, ref) => (
  <MUIMenuList ref={ref} {...props} />
)) as (props: MenuListProps) => JSX.Element
