// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type InputBaseProps = MUI.InputBaseProps
export const InputBase = (props: InputBaseProps) => <MUI.InputBase {...props} />
