// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIInputBase,
  InputBaseProps as MUIInputBaseProps,
} from '@material-ui/core/InputBase'
export type InputBaseProps = MUIInputBaseProps
export const InputBase = (props: InputBaseProps) => <MUIInputBase {...props} />
