// WARNING: This file is generated by a script, do not edit
import React from "react";
import {
  default as MUIInputBase,
  InputBaseProps as MUIInputBaseProps,
} from "@mui/material/InputBase";

/**
 * Props for InputBase
 */
export type InputBaseProps = MUIInputBaseProps & {
  ref?: React.ForwardedRef<unknown>;
};

/**
 * InputBase
 */
export const InputBase = React.forwardRef((props, ref) => (
  <MUIInputBase ref={ref} {...props} />
)) as (props: InputBaseProps) => JSX.Element;
