platform: linux
inputs:
- name: repo
- name: node-modules
  path: repo/node_modules
- name: yarn-cache
  path: repo/.yarn/cache
outputs:
- name: playroom
  path: repo/playroom
run:
  path: sh
  args:
    - -cx
    - |
      yarn install --immutable
      yarn build-playroom
  dir: repo