
platform: linux
inputs:
- name: repo
- name: pages
- name: playroom
outputs:
- name: pages
run:
  path: sh
  args:
    - -cx
    - |
      cd ../pages
      rm -rf ((git-branch-slug))/playroom
      mkdir -p ((git-branch-slug))/playroom
      cp -r ../playroom ./((git-branch-slug))
      git config --global user.email "concourseci@simspace.com"
      git config --global user.name "Concourse CI"
      git add . && git commit -m "ci: ((git-branch-slug)) playroom"
  dir: repo
