platform: linux
inputs:
  - name: repo
  - name: pages
  - name: storybook
outputs:
  - name: pages
run:
  path: bash
  args:
  - -eou
  - pipefail
  - -cx
  - |
    cd ../pages
    rm -rf ((git-branch-slug))/storybook
    mkdir -p ((git-branch-slug))
    cp -r ../storybook ./((git-branch-slug))
    git config --global user.email "concourseci@simspace.com"
    git config --global user.name "Concourse CI"
    git reset --soft HEAD^
    git add . && git commit -m "ci: pages"
  dir: repo
