platform: linux
inputs:
- name: repo
- name: pages
- name: storybook
outputs:
- name: pages
run:
  path: sh
  args:
    - -cx
    - |
      cd ../pages
      rm -rf ((git-branch-slug))/storybook
      mkdir -p ((git-branch-slug))
      cp -r ../storybook ./((git-branch-slug))
      git config --global user.email "concourseci@simspace.com"
      git config --global user.name "Concourse CI"
      git add . && git commit -m "ci: ((git-branch-slug)) storybook"
  dir: repo
