platform: linux
inputs:
- name: repo
- name: pages
- name: storybook
outputs:
- name: pages
run:
  path: sh
  args:
    - -cx
    - |
      GIT_BRANCH_SLUG=$(node ci/tasks/get-git-branch-slug.mjs)
      cd ../pages
      rm -rf storybook/$GIT_BRANCH_SLUG
      mkdir -p storybook/$GIT_BRANCH_SLUG
      cp -r ../storybook ./$GIT_BRANCH_SLUG
      git config --global user.email "<>"
      git config --global user.name "Concourse CI"
      git add . && git commit -m "ci: storybook $GIT_BRANCH_SLUG"
  dir: repo