
platform: linux
inputs:
- name: repo
- name: pages
- name: playroom
outputs:
- name: pages
run:
  path: sh
  args:
    - -cx
    - |
      GIT_BRANCH_SLUG=$(node ci/tasks/get-git-branch-slug.mjs)
      cd ../pages
      rm -rf $GIT_BRANCH_SLUG/playroom
      mkdir -p $GIT_BRANCH_SLUG/playroom
      cp -r ../playroom ./$GIT_BRANCH_SLUG
      git config --global user.email "concourseci@simspace.com"
      git config --global user.name "Concourse CI"
      git add . && git commit -m "ci: $GIT_BRANCH_SLUG playroom"
  dir: repo
