platform: linux
inputs:
- name: pages
outputs:
- name: pages
run:
  path: sh
  args:
  - -cx
  - |
    rm -rf ((git-branch-slug))
    git config --global user.email "concourseci@simspace.com"
    git config --global user.name "concourse ci"
    git reset --soft HEAD^
    git add . && git commit -m "ci: pages"
  dir: pages
