platform: linux
inputs:
- name: pages
outputs:
- name: pages
run:
  path: sh
  args:
  - -cx
  - |
    GIT_BRANCH_SLUG=$(node ci/tasks/get-git-branch-slug.mjs)
    rm -rf storybook/$GIT_BRANCH_SLUG
    git config --global user.email "<>"
    git config --global user.name "concourse ci"
    git add . && git commit -m "ci: delete artifacts $GIT_BRANCH_SLUG"
  dir: pages