platform: linux
inputs:
- name: repo
outputs:
- name: git-branch-slug
run:
  path: bash
  args:
  - -eou
  - pipefail
  - -cx
  - |
    node ci/tasks/get-git-branch-slug.mjs >> ../git-branch-slug/output
  dir: repo
