platform: linux
inputs:
- name: node-modules
  path: repo/node_modules
- name: yarn-cache
  path: repo/.yarn/cache
- name: components-build
- name: themes-build
- name: utils-build
- name: types-build
run:
  path: sh
  args:
  - -cx
  - |
    mv ../components-build/* packages/components
    mv ../utils-build/* packages/utils
    mv ../themes-build/* packages/themes
    mv ../types-build/* packages/types
    sh repo/tasks/publish.sh
  dir: repo
