// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { BottomNavigationTypeMap } from '@material-ui/core/BottomNavigation'
export type BottomNavigationProps<
  D extends React.ElementType = BottomNavigationTypeMap['defaultComponent'],
  P = {}
> = MUI.BottomNavigationProps<D, P>
export const BottomNavigation = <
  D extends React.ElementType = BottomNavigationTypeMap['defaultComponent'],
  P = {}
>(
  props: BottomNavigationProps<D, P>,
) => <MUI.BottomNavigation {...props} />
