// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIBottomNavigation,
  BottomNavigationProps as MUIBottomNavigationProps,
  BottomNavigationTypeMap,
} from '@mui/material/BottomNavigation'

/**
 * Props for BottomNavigation
 */
export type BottomNavigationProps<
  D extends React.ElementType = BottomNavigationTypeMap['defaultComponent'],
  P = {}
> = MUIBottomNavigationProps<D, P> & {
  ref?: React.ForwardedRef<HTMLDivElement>
}

/**
 * BottomNavigation
 */
export const BottomNavigation = React.forwardRef((props, ref) => (
  <MUIBottomNavigation ref={ref} {...props} />
)) as <
  D extends React.ElementType = BottomNavigationTypeMap['defaultComponent'],
  P = {}
>(
  props: BottomNavigationProps<D, P>,
) => JSX.Element
