// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { ImageListItemTypeMap } from '@material-ui/core/ImageListItem'
export type ImageListItemProps<
  D extends React.ElementType = ImageListItemTypeMap['defaultComponent'],
  P = {}
> = MUI.ImageListItemProps<D, P>
export const ImageListItem = <
  D extends React.ElementType = ImageListItemTypeMap['defaultComponent'],
  P = {}
>(
  props: ImageListItemProps<D, P>,
) => <MUI.ImageListItem {...props} />
