// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIImageListItem,
  ImageListItemProps as MUIImageListItemProps,
  ImageListItemTypeMap,
} from '@mui/material/ImageListItem'

/**
 * Props for ImageListItem
 */
export type ImageListItemProps<
  D extends React.ElementType = ImageListItemTypeMap['defaultComponent'],
  P = {}
> = MUIImageListItemProps<D, P> & { ref?: React.ForwardedRef<HTMLLIElement> }

/**
 * ImageListItem
 */
export const ImageListItem = React.forwardRef((props, ref) => (
  <MUIImageListItem ref={ref} {...props} />
)) as <
  D extends React.ElementType = ImageListItemTypeMap['defaultComponent'],
  P = {}
>(
  props: ImageListItemProps<D, P>,
) => JSX.Element
