// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUICardContent,
  CardContentProps as MUICardContentProps,
  CardContentTypeMap,
} from '@material-ui/core/CardContent'
export type CardContentProps<
  D extends React.ElementType = CardContentTypeMap['defaultComponent'],
  P = {}
> = MUICardContentProps<D, P>
export const CardContent = <
  D extends React.ElementType = CardContentTypeMap['defaultComponent'],
  P = {}
>(
  props: CardContentProps<D, P>,
) => <MUICardContent {...props} />
