// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { LinkTypeMap } from '@material-ui/core/Link'
export type LinkProps<
  D extends React.ElementType = LinkTypeMap['defaultComponent'],
  P = {}
> = MUI.LinkProps<D, P>
export const Link = <
  D extends React.ElementType = LinkTypeMap['defaultComponent'],
  P = {}
>(
  props: LinkProps<D, P>,
) => <MUI.Link {...props} />
