// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUILink,
  LinkProps as MUILinkProps,
  LinkTypeMap,
} from '@material-ui/core/Link'
export type LinkProps<
  D extends React.ElementType = LinkTypeMap['defaultComponent'],
  P = {}
> = MUILinkProps<D, P>
export const Link = <
  D extends React.ElementType = LinkTypeMap['defaultComponent'],
  P = {}
>(
  props: LinkProps<D, P>,
) => <MUILink {...props} />
