// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIStaticDatePicker,
  StaticDatePickerProps as MUIStaticDatePickerProps,
} from '@material-ui/lab/StaticDatePicker'

/**
 * Props for StaticDatePicker
 */
export type StaticDatePickerProps<
  TDate = unknown
> = MUIStaticDatePickerProps<TDate> & {
  ref?: React.ForwardedRef<HTMLDivElement>
}

/**
 * StaticDatePicker
 */
export const StaticDatePicker = React.forwardRef((props, ref) => (
  <MUIStaticDatePicker ref={ref} {...props} />
)) as <TDate = unknown>(props: StaticDatePickerProps<TDate>) => JSX.Element
