// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIPagination,
  PaginationProps as MUIPaginationProps,
} from '@material-ui/core/Pagination'
export type PaginationProps = MUIPaginationProps
export const Pagination = (props: PaginationProps) => (
  <MUIPagination {...props} />
)
