// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIPagination,
  PaginationProps as MUIPaginationProps,
} from '@material-ui/core/Pagination'

/**
 * Props for Pagination
 */
export type PaginationProps = MUIPaginationProps & {
  ref?: React.ForwardedRef<unknown>
}

/**
 * Pagination
 */
export const Pagination = React.forwardRef((props, ref) => (
  <MUIPagination ref={ref} {...props} />
)) as (props: PaginationProps) => JSX.Element
