// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  CalendarPickerProps as MUICalendarPickerProps,
  default as MUICalendarPicker,
} from '@mui/lab/CalendarPicker'

/**
 * Props for CalendarPicker
 */
export type CalendarPickerProps<TDate> = MUICalendarPickerProps<TDate> & {
  ref?: React.ForwardedRef<HTMLDivElement>
}

/**
 * CalendarPicker
 */
export const CalendarPicker = React.forwardRef((props, ref) => (
  <MUICalendarPicker ref={ref} {...props} />
)) as <TDate>(props: CalendarPickerProps<TDate>) => JSX.Element
