// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIRadioGroup,
  RadioGroupProps as MUIRadioGroupProps,
} from '@mui/material/RadioGroup'

/**
 * Props for RadioGroup
 */
export type RadioGroupProps = MUIRadioGroupProps & {
  ref?: React.ForwardedRef<unknown>
}

/**
 * RadioGroup
 */
export const RadioGroup = React.forwardRef((props, ref) => (
  <MUIRadioGroup ref={ref} {...props} />
)) as (props: RadioGroupProps) => JSX.Element
