// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIRadioGroup,
  RadioGroupProps as MUIRadioGroupProps,
} from '@material-ui/core/RadioGroup'
export type RadioGroupProps = MUIRadioGroupProps
export const RadioGroup = (props: RadioGroupProps) => (
  <MUIRadioGroup {...props} />
)
