// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUISlide,
  SlideProps as MUISlideProps,
} from '@material-ui/core/Slide'
export type SlideProps = MUISlideProps & { ref?: React.ForwardedRef<unknown> }
export const Slide = React.forwardRef((props, ref) => (
  <MUISlide ref={ref} {...props} />
)) as (props: SlideProps) => ReturnType<typeof MUISlide>
