// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUISlide,
  SlideProps as MUISlideProps,
} from '@material-ui/core/Slide'
export type SlideProps = MUISlideProps
export const Slide = (props: SlideProps) => <MUISlide {...props} />
