// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type SlideProps = MUI.SlideProps
export const Slide = (props: SlideProps) => <MUI.Slide {...props} />
