// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  AppBarProps as MUIAppBarProps,
  AppBarTypeMap,
  default as MUIAppBar,
} from '@mui/material/AppBar'

/**
 * Props for AppBar
 */
export type AppBarProps<
  D extends React.ElementType = AppBarTypeMap['defaultComponent'],
  P = {}
> = MUIAppBarProps<D, P> & { ref?: React.ForwardedRef<unknown> }

/**
 * AppBar
 */
export const AppBar = React.forwardRef((props, ref) => (
  <MUIAppBar ref={ref} {...props} />
)) as <D extends React.ElementType = AppBarTypeMap['defaultComponent'], P = {}>(
  props: AppBarProps<D, P>,
) => JSX.Element
