// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { AppBarTypeMap } from '@material-ui/core/AppBar'
export type AppBarProps<
  D extends React.ElementType = AppBarTypeMap['defaultComponent'],
  P = {}
> = MUI.AppBarProps<D, P>
export const AppBar = <
  D extends React.ElementType = AppBarTypeMap['defaultComponent'],
  P = {}
>(
  props: AppBarProps<D, P>,
) => <MUI.AppBar {...props} />
