// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIAppBar,
  AppBarProps as MUIAppBarProps,
  AppBarTypeMap,
} from '@material-ui/core/AppBar'
export type AppBarProps<
  D extends React.ElementType = AppBarTypeMap['defaultComponent'],
  P = {}
> = MUIAppBarProps<D, P>
export const AppBar = <
  D extends React.ElementType = AppBarTypeMap['defaultComponent'],
  P = {}
>(
  props: AppBarProps<D, P>,
) => <MUIAppBar {...props} />
