// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { GridTypeMap } from '@material-ui/core/Grid'
export type GridProps<
  D extends React.ElementType = GridTypeMap['defaultComponent'],
  P = {}
> = MUI.GridProps<D, P>
export const Grid = <
  D extends React.ElementType = GridTypeMap['defaultComponent'],
  P = {}
>(
  props: GridProps<D, P>,
) => <MUI.Grid {...props} />
