// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIGrid,
  GridProps as MUIGridProps,
  GridTypeMap,
} from '@material-ui/core/Grid'
export type GridProps<
  D extends React.ElementType = GridTypeMap['defaultComponent'],
  P = {}
> = MUIGridProps<D, P>
export const Grid = <
  D extends React.ElementType = GridTypeMap['defaultComponent'],
  P = {}
>(
  props: GridProps<D, P>,
) => <MUIGrid {...props} />
