// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { CardTypeMap } from '@material-ui/core/Card'
export type CardProps<
  D extends React.ElementType = CardTypeMap['defaultComponent'],
  P = {}
> = MUI.CardProps<D, P>
export const Card = <
  D extends React.ElementType = CardTypeMap['defaultComponent'],
  P = {}
>(
  props: CardProps<D, P>,
) => <MUI.Card {...props} />
