// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  CardProps as MUICardProps,
  CardTypeMap,
  default as MUICard,
} from '@mui/material/Card'

/**
 * Props for Card
 */
export type CardProps<
  D extends React.ElementType = CardTypeMap['defaultComponent'],
  P = {}
> = MUICardProps<D, P> & { ref?: React.ForwardedRef<unknown> }

/**
 * Card
 */
export const Card = React.forwardRef((props, ref) => (
  <MUICard ref={ref} {...props} />
)) as <D extends React.ElementType = CardTypeMap['defaultComponent'], P = {}>(
  props: CardProps<D, P>,
) => JSX.Element
