// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUITimeline,
  TimelineProps as MUITimelineProps,
} from '@material-ui/lab/Timeline'

/**
 * Props for Timeline
 */
export type TimelineProps = MUITimelineProps & {
  ref?: React.ForwardedRef<HTMLUListElement>
}

/**
 * Timeline
 */
export const Timeline = React.forwardRef((props, ref) => (
  <MUITimeline ref={ref} {...props} />
)) as (props: TimelineProps) => JSX.Element
