// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUITimeline,
  TimelineProps as MUITimelineProps,
} from '@mui/lab/Timeline'

/**
 * Props for Timeline
 */
export type TimelineProps = MUITimelineProps & {
  ref?: React.ForwardedRef<HTMLUListElement>
}

/**
 * Timeline
 */
export const Timeline = React.forwardRef(
  // TODO: This was hand edited to make it pass type-check - GS 01/12/22
  // The ref type was being inferred as 'unknown' instead of HTMLUListElement
  (props: TimelineProps, ref: React.Ref<HTMLUListElement> | undefined) => (
    <MUITimeline ref={ref} {...props} />
  ),
) as (props: TimelineProps) => JSX.Element
