// WARNING: This file is generated by a script, do not edit
import { DialogContentText } from '../DialogContentText'
/** This is intended to be exported (with possible extensions) as the default meta object for a story */
export const defaultStoryMeta = {
  title: 'Feedback/Dialog/DialogContentText',
  component: DialogContentText,
}
