// WARNING: This file is generated by a script, do not edit
import React from 'react'
import { story } from '../../../__tests__/helpers/storybook'
import { Skeleton, SkeletonProps } from '../Skeleton'
/** This is intended to be exported (with possible extensions) as the default meta object for a story */
export const defaultStoryMeta = {
  title: 'Feedback/Skeleton',
  component: Skeleton,
}
