// WARNING: This file is generated by a script, do not edit
import { Skeleton } from "../Skeleton";
/** This is intended to be exported (with possible extensions) as the default meta object for a story */
export const defaultStoryMeta = {
  title: "Feedback/Skeleton",
  component: Skeleton,
};
