// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIBottomNavigationAction,
  BottomNavigationActionProps as MUIBottomNavigationActionProps,
} from '@material-ui/core/BottomNavigationAction'
import { ButtonBaseTypeMap } from '@material-ui/core/ButtonBase'

/**
 * Props for BottomNavigationAction
 */
export type BottomNavigationActionProps<
  D extends React.ElementType = ButtonBaseTypeMap['defaultComponent'],
  P = {}
> = MUIBottomNavigationActionProps<D, P> & {
  ref?: React.ForwardedRef<HTMLButtonElement>
}

/**
 * BottomNavigationAction
 */
export const BottomNavigationAction = React.forwardRef((props, ref) => (
  <MUIBottomNavigationAction ref={ref} {...props} />
)) as <
  D extends React.ElementType = ButtonBaseTypeMap['defaultComponent'],
  P = {}
>(
  props: BottomNavigationActionProps<D, P>,
) => JSX.Element
