// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIBottomNavigationAction,
  BottomNavigationActionProps as MUIBottomNavigationActionProps,
} from '@material-ui/core/BottomNavigationAction'
import { ButtonBaseTypeMap } from '@material-ui/core/ButtonBase'
export type BottomNavigationActionProps<
  D extends React.ElementType = ButtonBaseTypeMap['defaultComponent'],
  P = {}
> = MUIBottomNavigationActionProps<D, P>
export const BottomNavigationAction = <
  D extends React.ElementType = ButtonBaseTypeMap['defaultComponent'],
  P = {}
>(
  props: BottomNavigationActionProps<D, P>,
) => <MUIBottomNavigationAction {...props} />
