// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { ButtonBaseTypeMap } from '@material-ui/core/ButtonBase'
export type BottomNavigationActionProps<
  D extends React.ElementType = ButtonBaseTypeMap['defaultComponent'],
  P = {}
> = MUI.BottomNavigationActionProps<D, P>
export const BottomNavigationAction = <
  D extends React.ElementType = ButtonBaseTypeMap['defaultComponent'],
  P = {}
>(
  props: BottomNavigationActionProps<D, P>,
) => <MUI.BottomNavigationAction {...props} />
