// WARNING: This file is generated by a script, do not edit
import React from "react";
import {
  AlertProps as MUIAlertProps,
  default as MUIAlert,
} from "@mui/material/Alert";

/**
 * Props for Alert
 */
export type AlertProps = MUIAlertProps & {
  ref?: React.ForwardedRef<HTMLDivElement>;
};

/**
 * Alert
 */
export const Alert = React.forwardRef((props, ref) => (
  <MUIAlert ref={ref} {...props} />
)) as (props: AlertProps) => JSX.Element;
