// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIAlert,
  AlertProps as MUIAlertProps,
} from '@material-ui/core/Alert'
export type AlertProps = MUIAlertProps & {
  ref?: React.ForwardedRef<HTMLDivElement>
}
export const Alert = React.forwardRef((props, ref) => (
  <MUIAlert ref={ref} {...props} />
)) as (props: AlertProps) => ReturnType<typeof MUIAlert>
