// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUINoSsr,
  NoSsrProps as MUINoSsrProps,
} from '@material-ui/core/NoSsr'
export type NoSsrProps = MUINoSsrProps
export const NoSsr = (props: NoSsrProps) => <MUINoSsr {...props} />
