// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIFormLabel,
  FormLabelProps as MUIFormLabelProps,
  FormLabelTypeMap,
} from '@material-ui/core/FormLabel'
export type FormLabelProps<
  D extends React.ElementType = FormLabelTypeMap['defaultComponent'],
  P = {}
> = MUIFormLabelProps<D, P>
export const FormLabel = <
  D extends React.ElementType = FormLabelTypeMap['defaultComponent'],
  P = {}
>(
  props: FormLabelProps<D, P>,
) => <MUIFormLabel {...props} />
