// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { FormLabelTypeMap } from '@material-ui/core/FormLabel'
export type FormLabelProps<
  D extends React.ElementType = FormLabelTypeMap['defaultComponent'],
  P = {}
> = MUI.FormLabelProps<D, P>
export const FormLabel = <
  D extends React.ElementType = FormLabelTypeMap['defaultComponent'],
  P = {}
>(
  props: FormLabelProps<D, P>,
) => <MUI.FormLabel {...props} />
