// WARNING: This file is generated by a script, do not edit
import { generateA11yStoryTests } from '../../../__tests__/helpers/a11y'
import * as stories from '../__stories__/AccordionActions.stories'
describe('AccordionActions (a11y))', () => {
  generateA11yStoryTests(stories)
})
