// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIStepConnector,
  StepConnectorProps as MUIStepConnectorProps,
} from '@material-ui/core/StepConnector'
export type StepConnectorProps = MUIStepConnectorProps
export const StepConnector = (props: StepConnectorProps) => (
  <MUIStepConnector {...props} />
)
