// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIStepLabel,
  StepLabelProps as MUIStepLabelProps,
} from '@material-ui/core/StepLabel'
export type StepLabelProps = MUIStepLabelProps
export const StepLabel = (props: StepLabelProps) => <MUIStepLabel {...props} />
