// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIStepLabel,
  StepLabelProps as MUIStepLabelProps,
} from '@mui/material/StepLabel'

/**
 * Props for StepLabel
 */
export type StepLabelProps = MUIStepLabelProps & {
  ref?: React.ForwardedRef<unknown>
}

/**
 * StepLabel
 */
export const StepLabel = React.forwardRef((props, ref) => (
  <MUIStepLabel ref={ref} {...props} />
)) as (props: StepLabelProps) => JSX.Element
