// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type StepLabelProps = MUI.StepLabelProps
export const StepLabel = (props: StepLabelProps) => <MUI.StepLabel {...props} />
