// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { TableBodyTypeMap } from '@material-ui/core/TableBody'
export type TableBodyProps<
  D extends React.ElementType = TableBodyTypeMap['defaultComponent'],
  P = {}
> = MUI.TableBodyProps<D, P>
export const TableBody = <
  D extends React.ElementType = TableBodyTypeMap['defaultComponent'],
  P = {}
>(
  props: TableBodyProps<D, P>,
) => <MUI.TableBody {...props} />
