// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUITooltip,
  TooltipProps as MUITooltipProps,
} from '@material-ui/core/Tooltip'
export type TooltipProps = MUITooltipProps & {
  ref?: React.ForwardedRef<HTMLDivElement>
}
export const Tooltip = React.forwardRef((props, ref) => (
  <MUITooltip ref={ref} {...props} />
)) as (props: TooltipProps) => ReturnType<typeof MUITooltip>
