// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUITooltip,
  TooltipProps as MUITooltipProps,
} from '@material-ui/core/Tooltip'
export type TooltipProps = MUITooltipProps
export const Tooltip = (props: TooltipProps) => <MUITooltip {...props} />
