// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUITab,
  TabProps as MUITabProps,
  TabTypeMap,
} from '@material-ui/core/Tab'
export type TabProps<
  D extends React.ElementType = TabTypeMap['defaultComponent'],
  P = {}
> = MUITabProps<D, P>
export const Tab = <
  D extends React.ElementType = TabTypeMap['defaultComponent'],
  P = {}
>(
  props: TabProps<D, P>,
) => <MUITab {...props} />
