// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUITab,
  TabProps as MUITabProps,
  TabTypeMap,
} from '@mui/material/Tab'

/**
 * Props for Tab
 */
export type TabProps<
  D extends React.ElementType = TabTypeMap['defaultComponent'],
  P = {}
> = MUITabProps<D, P> & { ref?: React.ForwardedRef<HTMLDivElement> }

/**
 * Tab
 */
export const Tab = React.forwardRef((props, ref) => (
  <MUITab ref={ref} {...props} />
)) as <D extends React.ElementType = TabTypeMap['defaultComponent'], P = {}>(
  props: TabProps<D, P>,
) => JSX.Element
