// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIIconButton,
  IconButtonProps as MUIIconButtonProps,
  IconButtonTypeMap,
} from '@mui/material/IconButton'

/**
 * Props for IconButton
 */
export type IconButtonProps<
  D extends React.ElementType = IconButtonTypeMap['defaultComponent'],
  P = {},
> = MUIIconButtonProps<D, P> & { ref?: React.ForwardedRef<HTMLButtonElement> }

/**
 * IconButton
 */
export const IconButton = React.forwardRef((props, ref) => (
  <MUIIconButton ref={ref} {...props} />
)) as <
  D extends React.ElementType = IconButtonTypeMap['defaultComponent'],
  P = {},
>(
  props: IconButtonProps<D, P>,
) => JSX.Element
