// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { IconButtonTypeMap } from '@material-ui/core/IconButton'
export type IconButtonProps<
  D extends React.ElementType = IconButtonTypeMap['defaultComponent'],
  P = {}
> = MUI.IconButtonProps<D, P>
export const IconButton = <
  D extends React.ElementType = IconButtonTypeMap['defaultComponent'],
  P = {}
>(
  props: IconButtonProps<D, P>,
) => <MUI.IconButton {...props} />
