// WARNING: This file is generated by a script, do not edit
import React from "react";
import {
  default as MUIMonthPicker,
  MonthPickerProps as MUIMonthPickerProps,
} from "@mui/lab/MonthPicker";

/**
 * Props for MonthPicker
 */
export type MonthPickerProps<TDate> = MUIMonthPickerProps<TDate> & {
  ref?: React.ForwardedRef<HTMLDivElement>;
};

/**
 * MonthPicker
 */
export const MonthPicker = React.forwardRef((props, ref) => (
  <MUIMonthPicker ref={ref} {...props} />
)) as <TDate>(props: MonthPickerProps<TDate>) => JSX.Element;
