// WARNING: This file is generated by a script, do not edit
import React from "react";
import {
  default as MUIPopover,
  PopoverProps as MUIPopoverProps,
} from "@mui/material/Popover";

/**
 * Props for Popover
 */
export type PopoverProps = MUIPopoverProps & {
  ref?: React.ForwardedRef<unknown>;
};

/**
 * Popover
 */
export const Popover = React.forwardRef((props, ref) => (
  <MUIPopover ref={ref} {...props} />
)) as (props: PopoverProps) => JSX.Element;
