// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIPopover,
  PopoverProps as MUIPopoverProps,
} from '@material-ui/core/Popover'
export type PopoverProps = MUIPopoverProps
export const Popover = (props: PopoverProps) => <MUIPopover {...props} />
