// WARNING: This file is generated by a script, do not edit
import { generateA11yStoryTests } from '../../../test-helpers/a11y'
import * as stories from '../__stories__/ScopedCssBaseline.stories'
describe('ScopedCssBaseline (a11y)', () => {
  generateA11yStoryTests(stories)
})
// Other hand-written tests should go in a separate file like "__tests__/ScopedCssBaseline.test.tsx"
