// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { FormControlTypeMap } from '@material-ui/core/FormControl'
export type FormControlProps<
  D extends React.ElementType = FormControlTypeMap['defaultComponent'],
  P = {}
> = MUI.FormControlProps<D, P>
export const FormControl = <
  D extends React.ElementType = FormControlTypeMap['defaultComponent'],
  P = {}
>(
  props: FormControlProps<D, P>,
) => <MUI.FormControl {...props} />
