// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIFormControl,
  FormControlProps as MUIFormControlProps,
  FormControlTypeMap,
} from '@mui/material/FormControl'

/**
 * Props for FormControl
 */
export type FormControlProps<
  D extends React.ElementType = FormControlTypeMap['defaultComponent'],
  P = {}
> = MUIFormControlProps<D, P> & { ref?: React.ForwardedRef<HTMLDivElement> }

/**
 * FormControl
 */
export const FormControl = React.forwardRef((props, ref) => (
  <MUIFormControl ref={ref} {...props} />
)) as <
  D extends React.ElementType = FormControlTypeMap['defaultComponent'],
  P = {}
>(
  props: FormControlProps<D, P>,
) => JSX.Element
