// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { ListItemButtonTypeMap } from '@material-ui/core/ListItemButton'
export type ListItemButtonProps<
  D extends React.ElementType = ListItemButtonTypeMap['defaultComponent'],
  P = {}
> = MUI.ListItemButtonProps<D, P>
export const ListItemButton = <
  D extends React.ElementType = ListItemButtonTypeMap['defaultComponent'],
  P = {}
>(
  props: ListItemButtonProps<D, P>,
) => <MUI.ListItemButton {...props} />
