// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type CardActionsProps = MUI.CardActionsProps
export const CardActions = (props: CardActionsProps) => (
  <MUI.CardActions {...props} />
)
