// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUISnackbarContent,
  SnackbarContentProps as MUISnackbarContentProps,
} from '@material-ui/core/SnackbarContent'
export type SnackbarContentProps = MUISnackbarContentProps
export const SnackbarContent = (props: SnackbarContentProps) => (
  <MUISnackbarContent {...props} />
)
