// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type SnackbarContentProps = MUI.SnackbarContentProps
export const SnackbarContent = (props: SnackbarContentProps) => (
  <MUI.SnackbarContent {...props} />
)
