// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUINativeSelect,
  NativeSelectProps as MUINativeSelectProps,
} from '@material-ui/core/NativeSelect'
export type NativeSelectProps = MUINativeSelectProps
export const NativeSelect = (props: NativeSelectProps) => (
  <MUINativeSelect {...props} />
)
