// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type ListItemProps<
  D extends React.ElementType = 'li',
  P = {}
> = MUI.ListItemProps<D, P>
export const ListItem = <D extends React.ElementType = 'li', P = {}>(
  props: ListItemProps<D, P>,
) => <MUI.ListItem {...props} />
