// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIDialog,
  DialogProps as MUIDialogProps,
} from '@material-ui/core/Dialog'
export type DialogProps = MUIDialogProps
export const Dialog = (props: DialogProps) => <MUIDialog {...props} />
