// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type DialogProps = MUI.DialogProps
export const Dialog = (props: DialogProps) => <MUI.Dialog {...props} />
