// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIDialog,
  DialogProps as MUIDialogProps,
} from '@material-ui/core/Dialog'
export type DialogProps = MUIDialogProps & {
  ref?: React.ForwardedRef<HTMLDivElement>
}
export const Dialog = React.forwardRef((props, ref) => (
  <MUIDialog ref={ref} {...props} />
)) as (props: DialogProps) => ReturnType<typeof MUIDialog>
