// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { SvgIconTypeMap } from '@material-ui/core/SvgIcon'
export type SvgIconProps<
  D extends React.ElementType = SvgIconTypeMap['defaultComponent'],
  P = {}
> = MUI.SvgIconProps<D, P>
export const SvgIcon = <
  D extends React.ElementType = SvgIconTypeMap['defaultComponent'],
  P = {}
>(
  props: SvgIconProps<D, P>,
) => <MUI.SvgIcon {...props} />
