// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUISvgIcon,
  SvgIconProps as MUISvgIconProps,
  SvgIconTypeMap,
} from '@mui/material/SvgIcon'

/**
 * Props for SvgIcon
 */
export type SvgIconProps<
  D extends React.ElementType = SvgIconTypeMap['defaultComponent'],
  P = {}
> = MUISvgIconProps<D, P> & { ref?: React.ForwardedRef<SVGSVGElement> }

/**
 * SvgIcon
 */
export const SvgIcon = React.forwardRef((props, ref) => (
  <MUISvgIcon ref={ref} {...props} />
)) as <
  D extends React.ElementType = SvgIconTypeMap['defaultComponent'],
  P = {}
>(
  props: SvgIconProps<D, P>,
) => JSX.Element
