// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUISvgIcon,
  SvgIconProps as MUISvgIconProps,
  SvgIconTypeMap,
} from '@material-ui/core/SvgIcon'
export type SvgIconProps<
  D extends React.ElementType = SvgIconTypeMap['defaultComponent'],
  P = {}
> = MUISvgIconProps<D, P>
export const SvgIcon = <
  D extends React.ElementType = SvgIconTypeMap['defaultComponent'],
  P = {}
>(
  props: SvgIconProps<D, P>,
) => <MUISvgIcon {...props} />
