// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIStack,
  StackProps as MUIStackProps,
  StackTypeMap,
} from '@mui/material/Stack'

/**
 * Props for Stack
 */
export type StackProps<
  D extends React.ElementType = StackTypeMap['defaultComponent'],
  P = {}
> = MUIStackProps<D, P> & { ref?: React.ForwardedRef<unknown> }

/**
 * Stack
 */
export const Stack = React.forwardRef((props, ref) => (
  <MUIStack ref={ref} {...props} />
)) as <D extends React.ElementType = StackTypeMap['defaultComponent'], P = {}>(
  props: StackProps<D, P>,
) => JSX.Element
