// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { StackTypeMap } from '@material-ui/core/Stack'
export type StackProps<
  D extends React.ElementType = StackTypeMap['defaultComponent'],
  P = {}
> = MUI.StackProps<D, P>
export const Stack = <
  D extends React.ElementType = StackTypeMap['defaultComponent'],
  P = {}
>(
  props: StackProps<D, P>,
) => <MUI.Stack {...props} />
