// WARNING: This file is generated by a script, do not edit
import React from "react";
import {
  default as MUITimelineItem,
  TimelineItemProps as MUITimelineItemProps,
} from "@mui/lab/TimelineItem";

/**
 * Props for TimelineItem
 */
export type TimelineItemProps = MUITimelineItemProps & {
  ref?: React.ForwardedRef<unknown>;
};

/**
 * TimelineItem
 */
export const TimelineItem = React.forwardRef((props, ref) => (
  <MUITimelineItem ref={ref} {...props} />
)) as (props: TimelineItemProps) => JSX.Element;
