// WARNING: This file is generated by a script, do not edit
import { generateA11yStoryTests } from '../../../__tests__/helpers/a11y'
import * as stories from '../__stories__/CircularProgress.stories'
describe('CircularProgress (a11y)', () => {
  generateA11yStoryTests(stories)
})
