// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type ZoomProps = MUI.ZoomProps
export const Zoom = (props: ZoomProps) => <MUI.Zoom {...props} />
