// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIZoom,
  ZoomProps as MUIZoomProps,
} from '@material-ui/core/Zoom'

/**
 * Props for Zoom
 */
export type ZoomProps = MUIZoomProps & { ref?: React.ForwardedRef<unknown> }

/**
 * Zoom
 */
export const Zoom = React.forwardRef((props, ref) => (
  <MUIZoom ref={ref} {...props} />
)) as (props: ZoomProps) => JSX.Element
