// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIZoom,
  ZoomProps as MUIZoomProps,
} from '@material-ui/core/Zoom'
export type ZoomProps = MUIZoomProps
export const Zoom = (props: ZoomProps) => <MUIZoom {...props} />
