// WARNING: This file is generated by a script, do not edit
import { SwipeableDrawer } from "../SwipeableDrawer";
/** This is intended to be exported (with possible extensions) as the default meta object for a story */
export const defaultStoryMeta = {
  title: "Navigation/Drawer/SwipeableDrawer",
  component: SwipeableDrawer,
};
