// WARNING: This file is generated by a script, do not edit
import React from "react";
import {
  AccordionDetailsProps as MUIAccordionDetailsProps,
  default as MUIAccordionDetails,
} from "@mui/material/AccordionDetails";

/**
 * Props for AccordionDetails
 */
export type AccordionDetailsProps = MUIAccordionDetailsProps & {
  ref?: React.ForwardedRef<unknown>;
};

/**
 * AccordionDetails
 */
export const AccordionDetails = React.forwardRef((props, ref) => (
  <MUIAccordionDetails ref={ref} {...props} />
)) as (props: AccordionDetailsProps) => JSX.Element;
