// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type AccordionDetailsProps = MUI.AccordionDetailsProps
export const AccordionDetails = (props: AccordionDetailsProps) => (
  <MUI.AccordionDetails {...props} />
)
