// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIAccordionDetails,
  AccordionDetailsProps as MUIAccordionDetailsProps,
} from '@material-ui/core/AccordionDetails'
export type AccordionDetailsProps = MUIAccordionDetailsProps
export const AccordionDetails = (props: AccordionDetailsProps) => (
  <MUIAccordionDetails {...props} />
)
