// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type ToggleButtonGroupProps = MUI.ToggleButtonGroupProps
export const ToggleButtonGroup = (props: ToggleButtonGroupProps) => (
  <MUI.ToggleButtonGroup {...props} />
)
