// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIToggleButtonGroup,
  ToggleButtonGroupProps as MUIToggleButtonGroupProps,
} from '@mui/material/ToggleButtonGroup'

/**
 * Props for ToggleButtonGroup
 */
export type ToggleButtonGroupProps = MUIToggleButtonGroupProps & {
  ref?: React.ForwardedRef<unknown>
}

/**
 * ToggleButtonGroup
 */
export const ToggleButtonGroup = React.forwardRef((props, ref) => (
  <MUIToggleButtonGroup ref={ref} {...props} />
)) as (props: ToggleButtonGroupProps) => JSX.Element
