// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIStepButton,
  StepButtonProps as MUIStepButtonProps,
} from '@material-ui/core/StepButton'
import { ButtonBaseTypeMap } from '@material-ui/core'
export type StepButtonProps<
  D extends React.ElementType = ButtonBaseTypeMap['defaultComponent'],
  P = {}
> = MUIStepButtonProps<D, P>
export const StepButton = <
  D extends React.ElementType = ButtonBaseTypeMap['defaultComponent'],
  P = {}
>(
  props: StepButtonProps<D, P>,
) => <MUIStepButton {...props} />
