// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIStepButton,
  StepButtonProps as MUIStepButtonProps,
} from '@material-ui/core/StepButton'
import { ButtonBaseTypeMap } from '@material-ui/core'

/**
 * Props for StepButton
 */
export type StepButtonProps<
  D extends React.ElementType = ButtonBaseTypeMap['defaultComponent'],
  P = {}
> = MUIStepButtonProps<D, P> & { ref?: React.ForwardedRef<HTMLButtonElement> }

/**
 * StepButton
 */
export const StepButton = React.forwardRef((props, ref) => (
  <MUIStepButton ref={ref} {...props} />
)) as <
  D extends React.ElementType = ButtonBaseTypeMap['defaultComponent'],
  P = {}
>(
  props: StepButtonProps<D, P>,
) => JSX.Element
