// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUISwipeableDrawer,
  SwipeableDrawerProps as MUISwipeableDrawerProps,
} from '@material-ui/core/SwipeableDrawer'
export type SwipeableDrawerProps = MUISwipeableDrawerProps
export const SwipeableDrawer = (props: SwipeableDrawerProps) => (
  <MUISwipeableDrawer {...props} />
)
