// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type MenuProps = MUI.MenuProps
export const Menu = (props: MenuProps) => <MUI.Menu {...props} />
