// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type SwitchProps = MUI.SwitchProps
export const Switch = (props: SwitchProps) => <MUI.Switch {...props} />
