// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUISwitch,
  SwitchProps as MUISwitchProps,
} from '@mui/material/Switch'

/**
 * Props for Switch
 */
export type SwitchProps = MUISwitchProps & {
  ref?: React.ForwardedRef<unknown>
}

/**
 * Switch
 */
export const Switch = React.forwardRef((props, ref) => (
  <MUISwitch ref={ref} {...props} />
)) as (props: SwitchProps) => JSX.Element
