// WARNING: This file is generated by a script, do not edit
import { Snackbar } from "../Snackbar";
/** This is intended to be exported (with possible extensions) as the default meta object for a story */
export const defaultStoryMeta = {
  title: "Feedback/Snackbar",
  component: Snackbar,
};
