// WARNING: This file is generated by a script, do not edit
import { Stepper } from '../Stepper'
/** This is intended to be exported (with possible extensions) as the default meta object for a story */
export const defaultStoryMeta = {
  title: 'Navigation/Stepper',
  component: Stepper,
}
