// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { ImageListTypeMap } from '@material-ui/core/ImageList'
export type ImageListProps<
  D extends React.ElementType = ImageListTypeMap['defaultComponent'],
  P = {}
> = MUI.ImageListProps<D, P>
export const ImageList = <
  D extends React.ElementType = ImageListTypeMap['defaultComponent'],
  P = {}
>(
  props: ImageListProps<D, P>,
) => <MUI.ImageList {...props} />
