// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIImageList,
  ImageListProps as MUIImageListProps,
  ImageListTypeMap,
} from '@material-ui/core/ImageList'
export type ImageListProps<
  D extends React.ElementType = ImageListTypeMap['defaultComponent'],
  P = {}
> = MUIImageListProps<D, P>
export const ImageList = <
  D extends React.ElementType = ImageListTypeMap['defaultComponent'],
  P = {}
>(
  props: ImageListProps<D, P>,
) => <MUIImageList {...props} />
