// WARNING: This file is generated by a script, do not edit
import { OutlinedInput } from "../OutlinedInput";
/** This is intended to be exported (with possible extensions) as the default meta object for a story */
export const defaultStoryMeta = {
  title: "Inputs/OutlinedInput",
  component: OutlinedInput,
};
