// WARNING: This file is generated by a script, do not edit
import { Toolbar } from "../Toolbar";
/** This is intended to be exported (with possible extensions) as the default meta object for a story */
export const defaultStoryMeta = { title: "Inputs/Toolbar", component: Toolbar };
