// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIDialogContent,
  DialogContentProps as MUIDialogContentProps,
} from '@material-ui/core/DialogContent'

/**
 * Props for DialogContent
 */
export type DialogContentProps = MUIDialogContentProps & {
  ref?: React.ForwardedRef<unknown>
}

/**
 * DialogContent
 */
export const DialogContent = React.forwardRef((props, ref) => (
  <MUIDialogContent ref={ref} {...props} />
)) as (props: DialogContentProps) => JSX.Element
