// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIDialogContent,
  DialogContentProps as MUIDialogContentProps,
} from '@material-ui/core/DialogContent'
export type DialogContentProps = MUIDialogContentProps
export const DialogContent = (props: DialogContentProps) => (
  <MUIDialogContent {...props} />
)
