// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type StepperProps = MUI.StepperProps
export const Stepper = (props: StepperProps) => <MUI.Stepper {...props} />
