// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIStepper,
  StepperProps as MUIStepperProps,
} from '@material-ui/core/Stepper'
export type StepperProps = MUIStepperProps
export const Stepper = (props: StepperProps) => <MUIStepper {...props} />
