// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type SnackbarProps = MUI.SnackbarProps
export const Snackbar = (props: SnackbarProps) => <MUI.Snackbar {...props} />
