// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUISnackbar,
  SnackbarProps as MUISnackbarProps,
} from '@material-ui/core/Snackbar'
export type SnackbarProps = MUISnackbarProps
export const Snackbar = (props: SnackbarProps) => <MUISnackbar {...props} />
