// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { BackdropTypeMap } from '@material-ui/core/Backdrop'
export type BackdropProps<
  D extends React.ElementType = BackdropTypeMap['defaultComponent'],
  P = {}
> = MUI.BackdropProps<D, P>
export const Backdrop = <
  D extends React.ElementType = BackdropTypeMap['defaultComponent'],
  P = {}
>(
  props: BackdropProps<D, P>,
) => <MUI.Backdrop {...props} />
