// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type InputLabelProps = MUI.InputLabelProps
export const InputLabel = (props: InputLabelProps) => (
  <MUI.InputLabel {...props} />
)
