// WARNING: This file is generated by a script, do not edit
import React from "react";
import {
  default as MUIInputLabel,
  InputLabelProps as MUIInputLabelProps,
} from "@mui/material/InputLabel";

/**
 * Props for InputLabel
 */
export type InputLabelProps = MUIInputLabelProps & {
  ref?: React.ForwardedRef<unknown>;
};

/**
 * InputLabel
 */
export const InputLabel = React.forwardRef((props, ref) => (
  <MUIInputLabel ref={ref} {...props} />
)) as (props: InputLabelProps) => JSX.Element;
