// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIDesktopDateTimePicker,
  DesktopDateTimePickerProps as MUIDesktopDateTimePickerProps,
} from '@mui/lab/DesktopDateTimePicker'

/**
 * Props for DesktopDateTimePicker
 */
export type DesktopDateTimePickerProps<
  TDate = unknown
> = MUIDesktopDateTimePickerProps<TDate> & {
  ref?: React.ForwardedRef<HTMLDivElement>
}

/**
 * DesktopDateTimePicker
 */
export const DesktopDateTimePicker = React.forwardRef((props, ref) => (
  <MUIDesktopDateTimePicker ref={ref} {...props} />
)) as <TDate = unknown>(props: DesktopDateTimePickerProps<TDate>) => JSX.Element
