// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUITreeView,
  TreeViewProps as MUITreeViewProps,
} from '@mui/lab/TreeView'

/**
 * Props for TreeView
 */
export type TreeViewProps = MUITreeViewProps & {
  ref?: React.ForwardedRef<unknown>
}

/**
 * TreeView
 */
export const TreeView = React.forwardRef((props, ref) => (
  <MUITreeView ref={ref} {...props} />
)) as (props: TreeViewProps) => JSX.Element
