// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type TablePaginationProps<
  D extends React.ElementType = React.JSXElementConstructor<TablePaginationBaseProps>,
  P = {}
> = MUI.TablePaginationProps<D, P>
export const TablePagination = <
  D extends React.ElementType = React.JSXElementConstructor<TablePaginationBaseProps>,
  P = {}
>(
  props: TablePaginationProps<D, P>,
) => <MUI.TablePagination {...props} />
