// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUITablePagination,
  TablePaginationProps as MUITablePaginationProps,
} from '@material-ui/core/TablePagination'
import { TablePaginationBaseProps } from '@material-ui/core/TablePagination'

/**
 * Props for TablePagination
 */
export type TablePaginationProps<
  D extends React.ElementType = React.JSXElementConstructor<TablePaginationBaseProps>,
  P = {}
> = MUITablePaginationProps<D, P> & { ref?: React.ForwardedRef<unknown> }

/**
 * TablePagination
 */
export const TablePagination = React.forwardRef((props, ref) => (
  <MUITablePagination ref={ref} {...props} />
)) as <
  D extends React.ElementType = React.JSXElementConstructor<TablePaginationBaseProps>,
  P = {}
>(
  props: TablePaginationProps<D, P>,
) => JSX.Element
