// WARNING: This file is generated by a script, do not edit
import React from "react";
import {
  default as MUIMobileDateTimePicker,
  MobileDateTimePickerProps as MUIMobileDateTimePickerProps,
} from "@mui/lab/MobileDateTimePicker";

/**
 * Props for MobileDateTimePicker
 */
export type MobileDateTimePickerProps<TDate = unknown> =
  MUIMobileDateTimePickerProps<TDate> & {
    ref?: React.ForwardedRef<HTMLDivElement>;
  };

/**
 * MobileDateTimePicker
 */
export const MobileDateTimePicker = React.forwardRef((props, ref) => (
  <MUIMobileDateTimePicker ref={ref} {...props} />
)) as <TDate = unknown>(props: MobileDateTimePickerProps<TDate>) => JSX.Element;
