// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIMobileDateRangePicker,
  MobileDateRangePickerProps as MUIMobileDateRangePickerProps,
} from '@material-ui/lab/MobileDateRangePicker'

/**
 * Props for MobileDateRangePicker
 */
export type MobileDateRangePickerProps<
  TDate = unknown
> = MUIMobileDateRangePickerProps<TDate> & { ref?: React.ForwardedRef<unknown> }

/**
 * MobileDateRangePicker
 */
export const MobileDateRangePicker = React.forwardRef((props, ref) => (
  // TODO: there is an issue with the ref type that needs to be investigated
  // @ts-ignore
  <MUIMobileDateRangePicker ref={ref} {...props} />
)) as <TDate = unknown>(props: MobileDateRangePickerProps<TDate>) => JSX.Element
