// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUITableRow,
  TableRowProps as MUITableRowProps,
  TableRowTypeMap,
} from '@material-ui/core/TableRow'
export type TableRowProps<
  D extends React.ElementType = TableRowTypeMap['defaultComponent'],
  P = {}
> = MUITableRowProps<D, P>
export const TableRow = <
  D extends React.ElementType = TableRowTypeMap['defaultComponent'],
  P = {}
>(
  props: TableRowProps<D, P>,
) => <MUITableRow {...props} />
