// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIDateRangePicker,
  DateRangePickerProps as MUIDateRangePickerProps,
} from '@material-ui/lab/DateRangePicker'

/**
 * Props for DateRangePicker
 */
export type DateRangePickerProps<TDate> = MUIDateRangePickerProps<TDate> & {
  ref?: React.ForwardedRef<HTMLDivElement>
}

/**
 * DateRangePicker
 */
export const DateRangePicker = React.forwardRef((props, ref) => (
  // TODO: there is an issue with the ref type that needs to be investigated
  // @ts-ignore
  <MUIDateRangePicker ref={ref} {...props} />
)) as <TDate>(props: DateRangePickerProps<TDate>) => JSX.Element
