// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUITable,
  TableProps as MUITableProps,
  TableTypeMap,
} from '@material-ui/core/Table'
export type TableProps<
  D extends React.ElementType = TableTypeMap['defaultComponent'],
  P = {}
> = MUITableProps<D, P>
export const Table = <
  D extends React.ElementType = TableTypeMap['defaultComponent'],
  P = {}
>(
  props: TableProps<D, P>,
) => <MUITable {...props} />
