// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUITable,
  TableProps as MUITableProps,
  TableTypeMap,
} from '@mui/material/Table'

/**
 * Props for Table
 */
export type TableProps<
  D extends React.ElementType = TableTypeMap['defaultComponent'],
  P = {},
> = MUITableProps<D, P> & { ref?: React.ForwardedRef<HTMLTableElement> }

/**
 * Table
 */
export const Table = React.forwardRef((props, ref) => (
  <MUITable ref={ref} {...props} />
)) as <D extends React.ElementType = TableTypeMap['defaultComponent'], P = {}>(
  props: TableProps<D, P>,
) => JSX.Element
