// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { SliderTypeMap } from '@material-ui/core/Slider'
export type SliderProps<
  D extends React.ElementType = SliderTypeMap['defaultComponent'],
  P = {}
> = MUI.SliderProps<D, P>
export const Slider = <
  D extends React.ElementType = SliderTypeMap['defaultComponent'],
  P = {}
>(
  props: SliderProps<D, P>,
) => <MUI.Slider {...props} />
