// WARNING: This file is generated by a script, do not edit
import React from "react";
import {
  default as MUISlider,
  SliderProps as MUISliderProps,
  SliderTypeMap,
} from "@mui/material/Slider";

/**
 * Props for Slider
 */
export type SliderProps<
  D extends React.ElementType = SliderTypeMap["defaultComponent"],
  P = {}
> = MUISliderProps<D, P> & { ref?: React.ForwardedRef<HTMLSpanElement> };

/**
 * Slider
 */
export const Slider = React.forwardRef((props, ref) => (
  <MUISlider ref={ref} {...props} />
)) as <D extends React.ElementType = SliderTypeMap["defaultComponent"], P = {}>(
  props: SliderProps<D, P>
) => JSX.Element;
