// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIMenuItem,
  MenuItemProps as MUIMenuItemProps,
  MenuItemTypeMap,
} from '@material-ui/core/MenuItem'
export type MenuItemProps<
  D extends React.ElementType = MenuItemTypeMap['defaultComponent'],
  P = {}
> = MUIMenuItemProps<D, P> & { ref?: React.ForwardedRef<HTMLLIElement> }
export const MenuItem = React.forwardRef((props, ref) => (
  <MUIMenuItem ref={ref} {...props} />
)) as <
  D extends React.ElementType = MenuItemTypeMap['defaultComponent'],
  P = {}
>(
  props: MenuItemProps<D, P>,
) => ReturnType<typeof MUIMenuItem>
