// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { MenuItemTypeMap } from '@material-ui/core/MenuItem'
export type MenuItemProps<
  D extends React.ElementType = MenuItemTypeMap['defaultComponent'],
  P = {}
> = MUI.MenuItemProps<D, P>
export const MenuItem = <
  D extends React.ElementType = MenuItemTypeMap['defaultComponent'],
  P = {}
>(
  props: MenuItemProps<D, P>,
) => <MUI.MenuItem {...props} />
