// WARNING: This file is generated by a script, do not edit
import { generateA11yStoryTests } from '../../helpers/a11y'
import * as stories from '../TextareaAutosize.stories'
describe('TextareaAutosize (a11y)', () => {
  generateA11yStoryTests(stories)
})
// Other hand-written tests should go in a separate file like "__tests__/TextareaAutosize.test.tsx"
