// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  AvatarGroupProps as MUIAvatarGroupProps,
  default as MUIAvatarGroup,
} from '@mui/material/AvatarGroup'

/**
 * Props for AvatarGroup
 */
export type AvatarGroupProps = MUIAvatarGroupProps & {
  ref?: React.ForwardedRef<unknown>
}

/**
 * AvatarGroup
 */
export const AvatarGroup = React.forwardRef((props, ref) => (
  <MUIAvatarGroup ref={ref} {...props} />
)) as (props: AvatarGroupProps) => JSX.Element
