// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIAvatarGroup,
  AvatarGroupProps as MUIAvatarGroupProps,
} from '@material-ui/core/AvatarGroup'
export type AvatarGroupProps = MUIAvatarGroupProps
export const AvatarGroup = (props: AvatarGroupProps) => (
  <MUIAvatarGroup {...props} />
)
