// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type AvatarGroupProps = MUI.AvatarGroupProps
export const AvatarGroup = (props: AvatarGroupProps) => (
  <MUI.AvatarGroup {...props} />
)
