// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  AccordionProps as MUIAccordionProps,
  default as MUIAccordion,
} from '@mui/material/Accordion'

/**
 * Props for Accordion
 */
export type AccordionProps = MUIAccordionProps & {
  ref?: React.ForwardedRef<HTMLDivElement>
}

/**
 * Accordion
 */
export const Accordion = React.forwardRef((props, ref) => (
  <MUIAccordion ref={ref} {...props} />
)) as (props: AccordionProps) => JSX.Element
