// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type AccordionProps = MUI.AccordionProps
export const Accordion = (props: AccordionProps) => <MUI.Accordion {...props} />
