// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIInput,
  InputProps as MUIInputProps,
} from '@material-ui/core/Input'
export type InputProps = MUIInputProps
export const Input = (props: InputProps) => <MUIInput {...props} />
