// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUITimelineDot,
  TimelineDotProps as MUITimelineDotProps,
} from '@mui/lab/TimelineDot'

/**
 * Props for TimelineDot
 */
export type TimelineDotProps = MUITimelineDotProps & {
  ref?: React.ForwardedRef<unknown>
}

/**
 * TimelineDot
 */
export const TimelineDot = React.forwardRef((props, ref) => (
  <MUITimelineDot ref={ref} {...props} />
)) as (props: TimelineDotProps) => JSX.Element
