// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUITableFooter,
  TableFooterProps as MUITableFooterProps,
  TableFooterTypeMap,
} from '@material-ui/core/TableFooter'
export type TableFooterProps<
  D extends React.ElementType = TableFooterTypeMap['defaultComponent'],
  P = {}
> = MUITableFooterProps<D, P>
export const TableFooter = <
  D extends React.ElementType = TableFooterTypeMap['defaultComponent'],
  P = {}
>(
  props: TableFooterProps<D, P>,
) => <MUITableFooter {...props} />
