// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUITimelineSeparator,
  TimelineSeparatorProps as MUITimelineSeparatorProps,
} from '@mui/lab/TimelineSeparator'

/**
 * Props for TimelineSeparator
 */
export type TimelineSeparatorProps = MUITimelineSeparatorProps & {
  ref?: React.ForwardedRef<unknown>
}

/**
 * TimelineSeparator
 */
export const TimelineSeparator = React.forwardRef((props, ref) => (
  <MUITimelineSeparator ref={ref} {...props} />
)) as (props: TimelineSeparatorProps) => JSX.Element
