// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type TableCellProps = MUI.TableCellProps
export const TableCell = (props: TableCellProps) => <MUI.TableCell {...props} />
