// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUITableCell,
  TableCellProps as MUITableCellProps,
} from '@material-ui/core/TableCell'

/**
 * Props for TableCell
 */
export type TableCellProps = MUITableCellProps & {
  ref?: React.ForwardedRef<unknown>
}

/**
 * TableCell
 */
export const TableCell = React.forwardRef((props, ref) => (
  <MUITableCell ref={ref} {...props} />
)) as (props: TableCellProps) => JSX.Element
