// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { TableSortLabelTypeMap } from '@material-ui/core/TableSortLabel'
export type TableSortLabelProps<
  D extends React.ElementType = TableSortLabelTypeMap['defaultComponent'],
  P = {}
> = MUI.TableSortLabelProps<D, P>
export const TableSortLabel = <
  D extends React.ElementType = TableSortLabelTypeMap['defaultComponent'],
  P = {}
>(
  props: TableSortLabelProps<D, P>,
) => <MUI.TableSortLabel {...props} />
