// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUITableSortLabel,
  TableSortLabelProps as MUITableSortLabelProps,
  TableSortLabelTypeMap,
} from '@mui/material/TableSortLabel'

/**
 * Props for TableSortLabel
 */
export type TableSortLabelProps<
  D extends React.ElementType = TableSortLabelTypeMap['defaultComponent'],
  P = {}
> = MUITableSortLabelProps<D, P> & { ref?: React.ForwardedRef<HTMLSpanElement> }

/**
 * TableSortLabel
 */
export const TableSortLabel = React.forwardRef((props, ref) => (
  <MUITableSortLabel ref={ref} {...props} />
)) as <
  D extends React.ElementType = TableSortLabelTypeMap['defaultComponent'],
  P = {}
>(
  props: TableSortLabelProps<D, P>,
) => JSX.Element
