// WARNING: This file is generated by a script, do not edit
import { Autocomplete } from '../Autocomplete'
/** This is intended to be exported (with possible extensions) as the default meta object for a story */
export const defaultStoryMeta = {
  title: 'Inputs/Autocomplete',
  component: Autocomplete,
}
