// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { ButtonGroupTypeMap } from '@material-ui/core/ButtonGroup'
export type ButtonGroupProps<
  D extends React.ElementType = ButtonGroupTypeMap['defaultComponent'],
  P = {}
> = MUI.ButtonGroupProps<D, P>
export const ButtonGroup = <
  D extends React.ElementType = ButtonGroupTypeMap['defaultComponent'],
  P = {}
>(
  props: ButtonGroupProps<D, P>,
) => <MUI.ButtonGroup {...props} />
