// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  ButtonGroupProps as MUIButtonGroupProps,
  ButtonGroupTypeMap,
  default as MUIButtonGroup,
} from '@mui/material/ButtonGroup'

/**
 * Props for ButtonGroup
 */
export type ButtonGroupProps<
  D extends React.ElementType = ButtonGroupTypeMap['defaultComponent'],
  P = {},
> = MUIButtonGroupProps<D, P> & { ref?: React.ForwardedRef<HTMLDivElement> }

/**
 * ButtonGroup
 */
export const ButtonGroup = React.forwardRef((props, ref) => (
  <MUIButtonGroup ref={ref} {...props} />
)) as <
  D extends React.ElementType = ButtonGroupTypeMap['defaultComponent'],
  P = {},
>(
  props: ButtonGroupProps<D, P>,
) => JSX.Element
