// WARNING: This file is generated by a script, do not edit
import { ImageListItemBar } from '../ImageListItemBar'
/** This is intended to be exported (with possible extensions) as the default meta object for a story */
export const defaultStoryMeta = {
  title: 'Layout/ImageList/ImageListItemBar',
  component: ImageListItemBar,
}
