// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type StepContentProps = MUI.StepContentProps
export const StepContent = (props: StepContentProps) => (
  <MUI.StepContent {...props} />
)
