// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIStepContent,
  StepContentProps as MUIStepContentProps,
} from '@material-ui/core/StepContent'
export type StepContentProps = MUIStepContentProps
export const StepContent = (props: StepContentProps) => (
  <MUIStepContent {...props} />
)
