// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIDialogTitle,
  DialogTitleProps as MUIDialogTitleProps,
} from '@material-ui/core/DialogTitle'
export type DialogTitleProps = MUIDialogTitleProps
export const DialogTitle = (props: DialogTitleProps) => (
  <MUIDialogTitle {...props} />
)
