// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type DialogTitleProps = MUI.DialogTitleProps
export const DialogTitle = (props: DialogTitleProps) => (
  <MUI.DialogTitle {...props} />
)
