// WARNING: This file is generated by a script, do not edit
import { GlobalStyles } from "../GlobalStyles";
/** This is intended to be exported (with possible extensions) as the default meta object for a story */
export const defaultStoryMeta = {
  title: "Utils/GlobalStyles",
  component: GlobalStyles,
};
