// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type PopperProps = MUI.PopperProps
export const Popper = (props: PopperProps) => <MUI.Popper {...props} />
