// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type CircularProgressProps = MUI.CircularProgressProps
export const CircularProgress = (props: CircularProgressProps) => (
  <MUI.CircularProgress {...props} />
)
