// WARNING: This file is generated by a script, do not edit
import React from "react";
import {
  CircularProgressProps as MUICircularProgressProps,
  default as MUICircularProgress,
} from "@mui/material/CircularProgress";

/**
 * Props for CircularProgress
 */
export type CircularProgressProps = MUICircularProgressProps & {
  ref?: React.ForwardedRef<unknown>;
};

/**
 * CircularProgress
 */
export const CircularProgress = React.forwardRef((props, ref) => (
  <MUICircularProgress ref={ref} {...props} />
)) as (props: CircularProgressProps) => JSX.Element;
