// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIAutocomplete,
  AutocompleteProps as MUIAutocompleteProps,
} from '@mui/material/Autocomplete'
import { ChipTypeMap } from '@mui/material/Chip'

/**
 * Props for Autocomplete
 */
export type AutocompleteProps<
  T,
  Multiple extends boolean | undefined,
  DisableClearable extends boolean | undefined,
  FreeSolo extends boolean | undefined,
  ChipComponent extends React.ElementType = ChipTypeMap['defaultComponent'],
> = MUIAutocompleteProps<
  T,
  Multiple,
  DisableClearable,
  FreeSolo,
  ChipComponent
> & { ref?: React.ForwardedRef<unknown> }

/**
 * Autocomplete
 */
export const Autocomplete = React.forwardRef((props, ref) => (
  <MUIAutocomplete ref={ref} {...props} />
)) as <
  T,
  Multiple extends boolean | undefined,
  DisableClearable extends boolean | undefined,
  FreeSolo extends boolean | undefined,
  ChipComponent extends React.ElementType = ChipTypeMap['defaultComponent'],
>(
  props: AutocompleteProps<
    T,
    Multiple,
    DisableClearable,
    FreeSolo,
    ChipComponent
  >,
) => JSX.Element
