// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIAutocomplete,
  AutocompleteProps as MUIAutocompleteProps,
} from '@material-ui/core/Autocomplete'
import { ChipTypeMap } from '@material-ui/core/Chip'
export type AutocompleteProps<
  T,
  Multiple extends boolean | undefined,
  DisableClearable extends boolean | undefined,
  FreeSolo extends boolean | undefined,
  ChipComponent extends React.ElementType = ChipTypeMap['defaultComponent']
> = MUIAutocompleteProps<T, Multiple, DisableClearable, FreeSolo, ChipComponent>
export const Autocomplete = <
  T,
  Multiple extends boolean | undefined,
  DisableClearable extends boolean | undefined,
  FreeSolo extends boolean | undefined,
  ChipComponent extends React.ElementType = ChipTypeMap['defaultComponent']
>(
  props: AutocompleteProps<
    T,
    Multiple,
    DisableClearable,
    FreeSolo,
    ChipComponent
  >,
) => <MUIAutocomplete {...props} />
