// WARNING: This file is generated by a script, do not edit
import React from 'react'
import { story } from '../../../__tests__/helpers/storybook'
import {
  StaticDateTimePicker,
  StaticDateTimePickerProps,
} from '../StaticDateTimePicker'
/** This is intended to be exported (with possible extensions) as the default meta object for a story */
export const defaultStoryMeta = {
  title: 'Inputs/Date and Time/StaticDateTimePicker',
  component: StaticDateTimePicker,
}
