// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIClickAwayListener,
  ClickAwayListenerProps as MUIClickAwayListenerProps,
} from '@material-ui/core/ClickAwayListener'
export type ClickAwayListenerProps = MUIClickAwayListenerProps
export const ClickAwayListener = (props: ClickAwayListenerProps) => (
  <MUIClickAwayListener {...props} />
)
