// WARNING: This file is generated by a script, do not edit
import React from "react";
import {
  ClickAwayListenerProps as MUIClickAwayListenerProps,
  default as MUIClickAwayListener,
} from "@mui/material/ClickAwayListener";

/**
 * Props for ClickAwayListener
 */
export type ClickAwayListenerProps = MUIClickAwayListenerProps & {
  ref?: React.ForwardedRef<unknown>;
};

/**
 * ClickAwayListener
 */
export const ClickAwayListener = React.forwardRef((props, ref) => (
  <MUIClickAwayListener ref={ref} {...props} />
)) as (props: ClickAwayListenerProps) => JSX.Element;
