// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUISkeleton,
  SkeletonProps as MUISkeletonProps,
  SkeletonTypeMap,
} from '@material-ui/core/Skeleton'
export type SkeletonProps<
  D extends React.ElementType = SkeletonTypeMap['defaultComponent'],
  P = {}
> = MUISkeletonProps<D, P>
export const Skeleton = <
  D extends React.ElementType = SkeletonTypeMap['defaultComponent'],
  P = {}
>(
  props: SkeletonProps<D, P>,
) => <MUISkeleton {...props} />
