// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { ListSubheaderTypeMap } from '@material-ui/core/ListSubheader'
export type ListSubheaderProps<
  D extends React.ElementType = ListSubheaderTypeMap['defaultComponent'],
  P = {}
> = MUI.ListSubheaderProps<D, P>
export const ListSubheader = <
  D extends React.ElementType = ListSubheaderTypeMap['defaultComponent'],
  P = {}
>(
  props: ListSubheaderProps<D, P>,
) => <MUI.ListSubheader {...props} />
