// WARNING: This file is generated by a script, do not edit
import React from "react";
import {
  default as MUIListSubheader,
  ListSubheaderProps as MUIListSubheaderProps,
  ListSubheaderTypeMap,
} from "@mui/material/ListSubheader";

/**
 * Props for ListSubheader
 */
export type ListSubheaderProps<
  D extends React.ElementType = ListSubheaderTypeMap["defaultComponent"],
  P = {}
> = MUIListSubheaderProps<D, P> & { ref?: React.ForwardedRef<HTMLLIElement> };

/**
 * ListSubheader
 */
export const ListSubheader = React.forwardRef((props, ref) => (
  <MUIListSubheader ref={ref} {...props} />
)) as <
  D extends React.ElementType = ListSubheaderTypeMap["defaultComponent"],
  P = {}
>(
  props: ListSubheaderProps<D, P>
) => JSX.Element;
