// WARNING: This file is generated by a script, do not edit
import { generateA11yStoryTests } from '../../helpers/a11y'
import * as stories from '../StaticDateRangePicker.stories'
describe('StaticDateRangePicker (a11y)', () => {
  generateA11yStoryTests(stories)
})
// Other hand-written tests should go in a separate file like "__tests__/StaticDateRangePicker.test.tsx"
