// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIChip,
  ChipProps as MUIChipProps,
  ChipTypeMap,
} from '@material-ui/core/Chip'

/**
 * Props for Chip
 */
export type ChipProps<
  D extends React.ElementType = ChipTypeMap['defaultComponent'],
  P = {}
> = MUIChipProps<D, P> & { ref?: React.ForwardedRef<HTMLDivElement> }

/**
 * Chip
 */
export const Chip = React.forwardRef((props, ref) => (
  <MUIChip ref={ref} {...props} />
)) as <D extends React.ElementType = ChipTypeMap['defaultComponent'], P = {}>(
  props: ChipProps<D, P>,
) => JSX.Element
