// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIChip,
  ChipProps as MUIChipProps,
  ChipTypeMap,
} from '@material-ui/core/Chip'
export type ChipProps<
  D extends React.ElementType = ChipTypeMap['defaultComponent'],
  P = {}
> = MUIChipProps<D, P>
export const Chip = <
  D extends React.ElementType = ChipTypeMap['defaultComponent'],
  P = {}
>(
  props: ChipProps<D, P>,
) => <MUIChip {...props} />
