// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { ChipTypeMap } from '@material-ui/core/Chip'
export type ChipProps<
  D extends React.ElementType = ChipTypeMap['defaultComponent'],
  P = {}
> = MUI.ChipProps<D, P>
export const Chip = <
  D extends React.ElementType = ChipTypeMap['defaultComponent'],
  P = {}
>(
  props: ChipProps<D, P>,
) => <MUI.Chip {...props} />
