// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUISelect,
  SelectProps as MUISelectProps,
} from '@material-ui/core/Select'
export type SelectProps<T extends unknown = unknown> = MUISelectProps<T>
export const Select = <T extends unknown = unknown>(props: SelectProps<T>) => (
  <MUISelect {...props} />
)
