// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUISelect,
  SelectProps as MUISelectProps,
} from '@mui/material/Select'

/**
 * Props for Select
 */
export type SelectProps<T extends unknown = unknown> = MUISelectProps<T> & {
  ref?: React.ForwardedRef<unknown>
}

/**
 * Select
 */
export const Select = React.forwardRef((props, ref) => (
  <MUISelect ref={ref} {...props} />
)) as <T extends unknown = unknown>(props: SelectProps<T>) => JSX.Element
