// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type SelectProps<T extends unknown = unknown> = MUI.SelectProps<T>
export const Select = <T extends unknown = unknown>(props: SelectProps<T>) => (
  <MUI.Select {...props} />
)
