// WARNING: This file is generated by a script, do not edit
import React from "react";
import {
  DataGrid as MUIDataGrid,
  DataGridProps as MUIDataGridProps,
} from "@mui/x-data-grid";

/**
 * Props for DataGrid
 */
export type DataGridProps = MUIDataGridProps & {
  ref?: React.ForwardedRef<HTMLDivElement>;
};

/**
 * DataGrid
 */
export const DataGrid = React.forwardRef((props, ref) => (
  <MUIDataGrid ref={ref} {...props} />
)) as (props: DataGridProps) => JSX.Element;

export * from "@mui/x-data-grid";
