// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIBadge,
  BadgeProps as MUIBadgeProps,
  BadgeTypeMap,
} from '@material-ui/core/Badge'
export type BadgeProps<
  D extends React.ElementType = BadgeTypeMap['defaultComponent'],
  P = {}
> = MUIBadgeProps<D, P>
export const Badge = <
  D extends React.ElementType = BadgeTypeMap['defaultComponent'],
  P = {}
>(
  props: BadgeProps<D, P>,
) => <MUIBadge {...props} />
