// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { BadgeTypeMap } from '@material-ui/core/Badge'
export type BadgeProps<
  D extends React.ElementType = BadgeTypeMap['defaultComponent'],
  P = {}
> = MUI.BadgeProps<D, P>
export const Badge = <
  D extends React.ElementType = BadgeTypeMap['defaultComponent'],
  P = {}
>(
  props: BadgeProps<D, P>,
) => <MUI.Badge {...props} />
