// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { AvatarTypeMap } from '@material-ui/core/Avatar'
export type AvatarProps<
  D extends React.ElementType = AvatarTypeMap['defaultComponent'],
  P = {}
> = MUI.AvatarProps<D, P>
export const Avatar = <
  D extends React.ElementType = AvatarTypeMap['defaultComponent'],
  P = {}
>(
  props: AvatarProps<D, P>,
) => <MUI.Avatar {...props} />
