// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIAvatar,
  AvatarProps as MUIAvatarProps,
  AvatarTypeMap,
} from '@material-ui/core/Avatar'

/**
 * Props for Avatar
 */
export type AvatarProps<
  D extends React.ElementType = AvatarTypeMap['defaultComponent'],
  P = {}
> = MUIAvatarProps<D, P> & { ref?: React.ForwardedRef<HTMLDivElement> }

/**
 * Avatar
 */
export const Avatar = React.forwardRef((props, ref) => (
  <MUIAvatar ref={ref} {...props} />
)) as <D extends React.ElementType = AvatarTypeMap['defaultComponent'], P = {}>(
  props: AvatarProps<D, P>,
) => JSX.Element
