// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIAvatar,
  AvatarProps as MUIAvatarProps,
  AvatarTypeMap,
} from '@material-ui/core/Avatar'
export type AvatarProps<
  D extends React.ElementType = AvatarTypeMap['defaultComponent'],
  P = {}
> = MUIAvatarProps<D, P>
export const Avatar = <
  D extends React.ElementType = AvatarTypeMap['defaultComponent'],
  P = {}
>(
  props: AvatarProps<D, P>,
) => <MUIAvatar {...props} />
