// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUISpeedDialIcon,
  SpeedDialIconProps as MUISpeedDialIconProps,
} from '@material-ui/core/SpeedDialIcon'
export type SpeedDialIconProps = MUISpeedDialIconProps
export const SpeedDialIcon = (props: SpeedDialIconProps) => (
  <MUISpeedDialIcon {...props} />
)
