// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUISpeedDialIcon,
  SpeedDialIconProps as MUISpeedDialIconProps,
} from '@material-ui/core/SpeedDialIcon'

/**
 * Props for SpeedDialIcon
 */
export type SpeedDialIconProps = MUISpeedDialIconProps & {
  ref?: React.ForwardedRef<unknown>
}

/**
 * SpeedDialIcon
 */
export const SpeedDialIcon = React.forwardRef((props, ref) => (
  <MUISpeedDialIcon ref={ref} {...props} />
)) as (props: SpeedDialIconProps) => JSX.Element
