// Edit this file to add new stories
import React from 'react'
// import { BarChart } from '@mui/x-charts/BarChart'
// import type { DataGridProps } from '@monorail/components'
import {
  axisClasses,
  BarPlot,
  // BarChart as MuiBarChart,
  ChartsXAxis,
  ChartsYAxis,
  LinePlot,
  PiePlot,
  ResponsiveChartContainer,
} from '@mui/x-charts'

import type { BarChartProps } from '@monorail/components'
import { BarChart, Box } from '@monorail/components'

// import * as Icons from '@monorail/components/icons'
import { story } from '../helpers/storybook.js'

export default {
  title: 'Charts/BarChart',
  component: BarChart,
  parameters: {
    creevey: {
      skip: 'Mismatch expected because data gets regenerated by mui/x-data-grid-generator.',
    },
  },
}

export const SimpleCharts = story<BarChartProps>(() => {
  return (
    <BarChart
      xAxis={[
        {
          id: 'barCategories',
          data: ['bar A', 'bar B', 'bar C'],
          scaleType: 'band',
        },
      ]}
      series={[
        {
          data: [2, 5, 3],
        },
      ]}
      width={500}
      height={300}
    />
  )
})

export const Composition = story(() => {
  return (
    <Box sx={{ width: '100%', maxWidth: 600 }}>
      <ResponsiveChartContainer
        xAxis={[
          {
            scaleType: 'band',
            data: ['Q1', 'Q2', 'Q3', 'Q4'],
            id: 'quarters',
            label: 'Quarters',
          },
        ]}
        yAxis={[{ id: 'money' }, { id: 'quantities' }]}
        series={[
          {
            type: 'line',
            id: 'revenue',
            yAxisKey: 'money',
            data: [5645, 7542, 9135, 12221],
          },
          {
            type: 'bar',
            id: 'cookies',
            yAxisKey: 'quantities',
            data: [3205, 2542, 3135, 8374],
          },
          {
            type: 'bar',
            id: 'icecream',
            yAxisKey: 'quantities',
            data: [1645, 5542, 5146, 3735],
          },
        ]}
        height={400}
        margin={{ left: 70, right: 70 }}
        sx={{
          [`.${axisClasses.left} .${axisClasses.label}`]: {
            transform: 'rotate(-90deg) translate(0px, -20px)',
          },
          [`.${axisClasses.right} .${axisClasses.label}`]: {
            transform: 'rotate(90deg) translate(0px, -25px)',
          },
        }}
      >
        <BarPlot />
        <PiePlot />
        <ChartsXAxis
          axisId="quarters"
          label="2021 quarters"
          labelFontSize={18}
        />
        <ChartsYAxis axisId="quantities" label="# units sold" />
        <ChartsYAxis axisId="money" position="right" label="revenue" />
      </ResponsiveChartContainer>
    </Box>
  )
})
