// WARNING: This file is generated by a script, do not edit
import { ClockPicker } from '../ClockPicker'
/** This is intended to be exported (with possible extensions) as the default meta object for a story */
export const defaultStoryMeta = {
  title: 'Inputs/Date and Time/ClockPicker',
  component: ClockPicker,
}
