// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type DialogActionsProps = MUI.DialogActionsProps
export const DialogActions = (props: DialogActionsProps) => (
  <MUI.DialogActions {...props} />
)
