// WARNING: This file is generated by a script, do not edit
import React from "react";
import {
  default as MUIDialogActions,
  DialogActionsProps as MUIDialogActionsProps,
} from "@mui/material/DialogActions";

/**
 * Props for DialogActions
 */
export type DialogActionsProps = MUIDialogActionsProps & {
  ref?: React.ForwardedRef<unknown>;
};

/**
 * DialogActions
 */
export const DialogActions = React.forwardRef((props, ref) => (
  <MUIDialogActions ref={ref} {...props} />
)) as (props: DialogActionsProps) => JSX.Element;
