// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIDialogActions,
  DialogActionsProps as MUIDialogActionsProps,
} from '@material-ui/core/DialogActions'
export type DialogActionsProps = MUIDialogActionsProps
export const DialogActions = (props: DialogActionsProps) => (
  <MUIDialogActions {...props} />
)
