// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUITimelineOppositeContent,
  TimelineOppositeContentProps as MUITimelineOppositeContentProps,
} from '@mui/lab/TimelineOppositeContent'

/**
 * Props for TimelineOppositeContent
 */
export type TimelineOppositeContentProps = MUITimelineOppositeContentProps & {
  ref?: React.ForwardedRef<HTMLButtonElement>
}

/**
 * TimelineOppositeContent
 */
export const TimelineOppositeContent = React.forwardRef((props, ref) => (
  <MUITimelineOppositeContent ref={ref} {...props} />
)) as (props: TimelineOppositeContentProps) => JSX.Element
