// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type OutlinedInputProps = MUI.OutlinedInputProps
export const OutlinedInput = (props: OutlinedInputProps) => (
  <MUI.OutlinedInput {...props} />
)
