// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIOutlinedInput,
  OutlinedInputProps as MUIOutlinedInputProps,
} from '@mui/material/OutlinedInput'

/**
 * Props for OutlinedInput
 */
export type OutlinedInputProps = MUIOutlinedInputProps & {
  ref?: React.ForwardedRef<unknown>
}

/**
 * OutlinedInput
 */
export const OutlinedInput = React.forwardRef((props, ref) => (
  <MUIOutlinedInput ref={ref} {...props} />
)) as (props: OutlinedInputProps) => JSX.Element
