// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { DividerTypeMap } from '@material-ui/core/Divider'
export type DividerProps<
  D extends React.ElementType = DividerTypeMap['defaultComponent'],
  P = {}
> = MUI.DividerProps<D, P>
export const Divider = <
  D extends React.ElementType = DividerTypeMap['defaultComponent'],
  P = {}
>(
  props: DividerProps<D, P>,
) => <MUI.Divider {...props} />
