// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIDesktopDateRangePicker,
  DesktopDateRangePickerProps as MUIDesktopDateRangePickerProps,
} from '@material-ui/lab/DesktopDateRangePicker'

/**
 * Props for DesktopDateRangePicker
 */
export type DesktopDateRangePickerProps<
  TDate = unknown
> = MUIDesktopDateRangePickerProps<TDate> & {
  ref?: React.ForwardedRef<unknown>
}

/**
 * DesktopDateRangePicker
 */
export const DesktopDateRangePicker = React.forwardRef((props, ref) => (
  // TODO: there is an issue with the ref type that needs to be investigated
  // @ts-ignore
  <MUIDesktopDateRangePicker ref={ref} {...props} />
)) as <TDate = unknown>(
  props: DesktopDateRangePickerProps<TDate>,
) => JSX.Element
