// WARNING: This file is generated by a script, do not edit
import React from "react";
import {
  CssBaselineProps as MUICssBaselineProps,
  default as MUICssBaseline,
} from "@mui/material/CssBaseline";

/**
 * Props for CssBaseline
 */
export type CssBaselineProps = MUICssBaselineProps & {
  ref?: React.ForwardedRef<unknown>;
};

/**
 * CssBaseline
 */
export const CssBaseline = React.forwardRef((props, ref) => (
  <MUICssBaseline ref={ref} {...props} />
)) as (props: CssBaselineProps) => JSX.Element;
