// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUICssBaseline,
  CssBaselineProps as MUICssBaselineProps,
} from '@material-ui/core/CssBaseline'
export type CssBaselineProps = MUICssBaselineProps
export const CssBaseline = (props: CssBaselineProps) => (
  <MUICssBaseline {...props} />
)
