// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type CssBaselineProps = MUI.CssBaselineProps
export const CssBaseline = (props: CssBaselineProps) => (
  <MUI.CssBaseline {...props} />
)
