// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIContainer,
  ContainerProps as MUIContainerProps,
  ContainerTypeMap,
} from '@material-ui/core/Container'
export type ContainerProps<
  D extends React.ElementType = ContainerTypeMap['defaultComponent'],
  P = {}
> = MUIContainerProps<D, P>
export const Container = <
  D extends React.ElementType = ContainerTypeMap['defaultComponent'],
  P = {}
>(
  props: ContainerProps<D, P>,
) => <MUIContainer {...props} />
