// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { ContainerTypeMap } from '@material-ui/core/Container'
export type ContainerProps<
  D extends React.ElementType = ContainerTypeMap['defaultComponent'],
  P = {}
> = MUI.ContainerProps<D, P>
export const Container = <
  D extends React.ElementType = ContainerTypeMap['defaultComponent'],
  P = {}
>(
  props: ContainerProps<D, P>,
) => <MUI.Container {...props} />
