// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIContainer,
  ContainerProps as MUIContainerProps,
  ContainerTypeMap,
} from '@material-ui/core/Container'

/**
 * Props for Container
 */
export type ContainerProps<
  D extends React.ElementType = ContainerTypeMap['defaultComponent'],
  P = {}
> = MUIContainerProps<D, P> & { ref?: React.ForwardedRef<HTMLDivElement> }

/**
 * Container
 */
export const Container = React.forwardRef((props, ref) => (
  <MUIContainer ref={ref} {...props} />
)) as <
  D extends React.ElementType = ContainerTypeMap['defaultComponent'],
  P = {}
>(
  props: ContainerProps<D, P>,
) => JSX.Element
