// WARNING: This file is generated by a script, do not edit
import React from "react";
import {
  default as MUISpeedDialAction,
  SpeedDialActionProps as MUISpeedDialActionProps,
} from "@mui/material/SpeedDialAction";

/**
 * Props for SpeedDialAction
 */
export type SpeedDialActionProps = MUISpeedDialActionProps & {
  ref?: React.ForwardedRef<unknown>;
};

/**
 * SpeedDialAction
 */
export const SpeedDialAction = React.forwardRef((props, ref) => (
  <MUISpeedDialAction ref={ref} {...props} />
)) as (props: SpeedDialActionProps) => JSX.Element;
