// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUISpeedDialAction,
  SpeedDialActionProps as MUISpeedDialActionProps,
} from '@material-ui/core/SpeedDialAction'
export type SpeedDialActionProps = MUISpeedDialActionProps
export const SpeedDialAction = (props: SpeedDialActionProps) => (
  <MUISpeedDialAction {...props} />
)
