// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUISpeedDial,
  SpeedDialProps as MUISpeedDialProps,
} from '@material-ui/core/SpeedDial'

/**
 * Props for SpeedDial
 */
export type SpeedDialProps = MUISpeedDialProps & {
  ref?: React.ForwardedRef<unknown>
}

/**
 * SpeedDial
 */
export const SpeedDial = React.forwardRef((props, ref) => (
  <MUISpeedDial ref={ref} {...props} />
)) as (props: SpeedDialProps) => JSX.Element
