// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type SpeedDialProps = MUI.SpeedDialProps
export const SpeedDial = (props: SpeedDialProps) => <MUI.SpeedDial {...props} />
