// WARNING: This file is generated by a script, do not edit
import React from 'react'

import { story } from '../../../__tests__/helpers/storybook'
import { MobileDatePicker, MobileDatePickerProps } from '../MobileDatePicker'
/** This is intended to be exported (with possible extensions) as the default meta object for a story */
export const defaultStoryMeta = {
  title: 'Inputs/Date and Time/MobileDatePicker',
  component: MobileDatePicker,
}
