// WARNING: This file is generated by a script, do not edit
import React from "react";
import {
  default as MUIFilledInput,
  FilledInputProps as MUIFilledInputProps,
} from "@mui/material/FilledInput";

/**
 * Props for FilledInput
 */
export type FilledInputProps = MUIFilledInputProps & {
  ref?: React.ForwardedRef<unknown>;
};

/**
 * FilledInput
 */
export const FilledInput = React.forwardRef((props, ref) => (
  <MUIFilledInput ref={ref} {...props} />
)) as (props: FilledInputProps) => JSX.Element;
