// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIFilledInput,
  FilledInputProps as MUIFilledInputProps,
} from '@material-ui/core/FilledInput'
export type FilledInputProps = MUIFilledInputProps
export const FilledInput = (props: FilledInputProps) => (
  <MUIFilledInput {...props} />
)
