// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  DatePickerProps as MUIDatePickerProps,
  default as MUIDatePicker,
} from '@mui/lab/DatePicker'

/**
 * Props for DatePicker
 */
export type DatePickerProps<TDate = unknown> = MUIDatePickerProps<TDate> & {
  ref?: React.ForwardedRef<HTMLDivElement>
}

/**
 * DatePicker
 */
export const DatePicker = React.forwardRef((props, ref) => (
  <MUIDatePicker ref={ref} {...props} />
)) as <TDate = unknown>(props: DatePickerProps<TDate>) => JSX.Element
