// WARNING: This file is generated by a script, do not edit
import React from "react";
import {
  default as MUIIcon,
  IconProps as MUIIconProps,
  IconTypeMap,
} from "@mui/material/Icon";

/**
 * Props for Icon
 */
export type IconProps<
  D extends React.ElementType = IconTypeMap["defaultComponent"],
  P = {}
> = MUIIconProps<D, P> & { ref?: React.ForwardedRef<HTMLSpanElement> };

/**
 * Icon
 */
export const Icon = React.forwardRef((props, ref) => (
  <MUIIcon ref={ref} {...props} />
)) as <D extends React.ElementType = IconTypeMap["defaultComponent"], P = {}>(
  props: IconProps<D, P>
) => JSX.Element;
