// WARNING: This file is generated by a script, do not edit
import { generateA11yStoryTests } from '../../helpers/a11y'
import * as stories from '../Breadcrumbs.stories'
describe('Breadcrumbs (a11y)', () => {
  generateA11yStoryTests(stories)
})
// Other hand-written tests should go in a separate file like "__tests__/Breadcrumbs.test.tsx"
