// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIStep,
  StepProps as MUIStepProps,
} from '@material-ui/core/Step'
export type StepProps = MUIStepProps
export const Step = (props: StepProps) => <MUIStep {...props} />
