// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type StepProps = MUI.StepProps
export const Step = (props: StepProps) => <MUI.Step {...props} />
