// WARNING: This file is generated by a script, do not edit
import { generateA11yStoryTests } from '../../../__tests__/helpers/a11y'
import * as stories from '../__stories__/Link.stories'
describe('Link (a11y)', () => {
  generateA11yStoryTests(stories)
})
// Other hand-written tests should go in a separate file like "__tests__/Link.test.tsx"
