// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type TextareaAutosizeProps = MUI.TextareaAutosizeProps
export const TextareaAutosize = (props: TextareaAutosizeProps) => (
  <MUI.TextareaAutosize {...props} />
)
