// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUICheckbox,
  CheckboxProps as MUICheckboxProps,
} from '@material-ui/core/Checkbox'
export type CheckboxProps = MUICheckboxProps
export const Checkbox = (props: CheckboxProps) => <MUICheckbox {...props} />
