// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type CheckboxProps = MUI.CheckboxProps
export const Checkbox = (props: CheckboxProps) => <MUI.Checkbox {...props} />
