// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIGrow,
  GrowProps as MUIGrowProps,
} from '@material-ui/core/Grow'
export type GrowProps = MUIGrowProps
export const Grow = (props: GrowProps) => <MUIGrow {...props} />
