// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
import { ToggleButtonTypeMap } from '@material-ui/core/ToggleButton'
export type ToggleButtonProps<
  D extends React.ElementType = ToggleButtonTypeMap['defaultComponent'],
  P = {}
> = MUI.ToggleButtonProps<D, P>
export const ToggleButton = <
  D extends React.ElementType = ToggleButtonTypeMap['defaultComponent'],
  P = {}
>(
  props: ToggleButtonProps<D, P>,
) => <MUI.ToggleButton {...props} />
