// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type RatingProps = MUI.RatingProps
export const Rating = (props: RatingProps) => <MUI.Rating {...props} />
