// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIRating,
  RatingProps as MUIRatingProps,
} from '@material-ui/core/Rating'
export type RatingProps = MUIRatingProps
export const Rating = (props: RatingProps) => <MUIRating {...props} />
