// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIFormControlLabel,
  FormControlLabelProps as MUIFormControlLabelProps,
} from '@material-ui/core/FormControlLabel'
export type FormControlLabelProps = MUIFormControlLabelProps
export const FormControlLabel = (props: FormControlLabelProps) => (
  <MUIFormControlLabel {...props} />
)
