// WARNING: This file is generated by a script, do not edit
import React from 'react'
import * as MUI from '@material-ui/core'
export type ImageListItemBarProps = MUI.ImageListItemBarProps
export const ImageListItemBar = (props: ImageListItemBarProps) => (
  <MUI.ImageListItemBar {...props} />
)
