// WARNING: This file is generated by a script, do not edit
import React from 'react'
import {
  default as MUIImageListItemBar,
  ImageListItemBarProps as MUIImageListItemBarProps,
} from '@material-ui/core/ImageListItemBar'
export type ImageListItemBarProps = MUIImageListItemBarProps
export const ImageListItemBar = (props: ImageListItemBarProps) => (
  <MUIImageListItemBar {...props} />
)
